### ISSUE TITLE
Bind variables to lookahead values

### ISSUE THREAD

**Issue by ihrwein** [kevinmehall/rust-peg#104]
Can I bind variables to the values of lookahead expressions? Like:

```
foo -> &'input str
  = var:&bar { var }
```

So it'd return the value of the `bar` expression, without consuming the input. I tried it, but `match_str` is empty and `var` is the unit value.

Thanks for your help and this great library!

**Comment by jonas-schievink** [comment]
Doesn't look like it. Positive/Negative lookahead [always](https://github.com/kevinmehall/rust-peg/blob/fc49125552f43509c7c5a87ee094a592152f3231/src/translate.rs#L604) returns `()`. But this does indeed sound useful.
