### ISSUE TITLE
rust-peg broken on nightly build

### ISSUE THREAD

**Issue by loganmhb** [kevinmehall/rust-peg#110]
A breaking change to syntax::ext::base::ExtCtxt::new(), requiring an additional argument, seems to be preventing rust-peg from building on the latest nightly: https://github.com/rust-lang/rust/commit/e364f0eb5a51a96932ecd01dd2319eff4bdae2d1#diff-5100da09ad52c81568562e36ee359343

I get this error:

    $ cargo build
       Compiling peg v0.3.1 (file:///Users/lbuckley/Development/rust-peg)
    src/fake_extctxt.rs:9:16: 11:4 error: this function takes 4 parameters but 3 parameters were supplied [E0061]
    src/fake_extctxt.rs: 9   let mut cx = syntax::ext::base::ExtCtxt::new(&ps, Vec::new(),
    src/fake_extctxt.rs:10     syntax::ext::expand::ExpansionConfig::default("rust-peg".to_string())
    src/fake_extctxt.rs:11   );
    src/fake_extctxt.rs:9:16: 11:4 help: run `rustc --explain E0061` to see a detailed explanation
    error: aborting due to previous error
    Could not compile `peg`.

I am very new to Rust, but the fix seems to be simply adding a new `Vec::<GatedCfg>` to the call to ExtCtxt::new(). After making that change locally the build succeeds and the command line tool seems to work, though I am having trouble getting the compiler plugin to load, so I don't know if the tests work or not. I will poke at that a bit more and put up a PR of some kind.

**Comment by kevinmehall** [comment]
Closed by 140fa15
