### ISSUE TITLE
Support for generic type parameters

### ISSUE THREAD

**Issue by ihrwein** [kevinmehall/rust-peg#113]
Hi,

First of all, thanks for this great library :)

I'd like to instantiate different implementations of objects with the same grammar. This is like an abstract factory where the grammar uses the factory to create the objects.

If I could define a generic type parameter with a bound on a `pub` generated function then I could use the factory.

What do you think about this use-case?

UPDATE:
This issue is orthogonal to #84 because I don't need an extra argument to the functions just an `<T: Factory>` generic type parameter on the generated functions. My `Factory` has only static methods.

**Comment by kevinmehall** [comment]
[0.6.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) supports type parameters and arguments on rules.
