### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by y-ich** [kevinmehall/rust-peg#118]
I don't know from when, the macro panictry is not exported by libsyntax, so currently rust-peg can not be built.
rustc 1.7.0-nightly (81ae8be71 2015-12-09)

**Comment by kevinmehall** [comment]
Update to the latest nightly -- it's working in `rustc 1.7.0-nightly (4744472fe 2016-01-02)`

**Comment by y-ich** [comment]
Thanks!

**Comment by lyuts** [comment]
Are there any plans in the long term to move away from using panictry? According to rust's code this macro is temporary.

**Comment by kevinmehall** [comment]
It's all going to be rewritten once the [new macro API](http://www.ncameron.org/blog/libmacro/) is implemented.

**Comment by lyuts** [comment]
Cool. And thank you for the link.
