### ISSUE TITLE
Fails to build on latest rust nightly

### ISSUE THREAD

**Issue by FredrikNoren** [kevinmehall/rust-peg#119]
rustc 1.7.0-nightly (d5e229057 2016-01-04) can't build peg

**Comment by crazymykl** [comment]
How about a traceback of the failure?

**Comment by FredrikNoren** [comment]
Hm actually seems like it is building: https://github.com/kevinmehall/rust-peg/pull/120

Something else must be wrong on my end, sorry for the confusion
