### ISSUE TITLE
Make it possible to run peg as part of build script

### ISSUE THREAD

**Issue by FredrikNoren** [kevinmehall/rust-peg#121]
For some reason using peg in nightly makes cargo want to re-compile everything each time, so I tried using peg as part of a build script instead (http://doc.crates.io/build-script.html). I'll post a PR for this.

**Comment by kevinmehall** [comment]
BTW, 332fd4d fixes the "re-compile everything each time" issue. I'd noticed that issue in one of my projects that uses this library, but hadn't blamed it on `peg` yet, so this prompted me to track it down.

**Comment by FredrikNoren** [comment]
Oh that's awesome! Can we get a new release for the fix?

**Comment by FredrikNoren** [comment]
Ok all works for me now. I'll leave this open though since I think it would still be useful to make it possible to run this as a build script, at least while the rust plugin stuff is still only in nightly.

**Comment by kevinmehall** [comment]
Implemented in 0.4.
