### ISSUE TITLE
Is there anyway to match against the start/end of the input string?

### ISSUE THREAD

**Issue by rory** [kevinmehall/rust-peg#124]
For somethings I'm doing, it would be helpful to be able to match against the start or end of the input string. I can't see anyway to do this, is it possible?

**Comment by kevinmehall** [comment]
You can match the end of string by defining a rule `EOF = !.` because `.` can't match another character at the end of string.

What's your use case for matching the start of string? You could put whatever needs to be at the start of string at the beginning of the toplevel rule.

**Comment by rory** [comment]
> You can match the end of string by defining a rule EOF = !. because . can't match another character at the end of string.

That actually sounds very sensible, thanks.

> What's your use case for matching the start of string? You could put whatever needs to be at the start of string at the beginning of the toplevel rule.

Initially I had some trouble parsing and I thought it could be helped with a EOF match, but after using that trick, it doesn't work, so maybe something else is wrong.

I am trying to parse wikipedia style structured documents, which uses `==TITLE==` and `===SUBHEADING===` type structure.

A sample code looks like this:

    #![feature(plugin)]
    #![plugin(peg_syntax_ext)]
    
    use std::collections::HashMap;
    
    peg! layout(r#"
    use std::collections::HashMap;
    use std::iter::FromIterator;
    
    #[pub]
    body -> HashMap<&'input str, HashMap<&'input str, &'input str>> = t:title_sections ** "\n" { HashMap::from_iter(t) }
    title_sections -> (&'input str, HashMap<&'input str, &'input str>) = "==" t:title "==\n" s:subheadings { (t, s) }
    title -> &'input str = [a-zA-Z0-9]+ { match_str }
    subheadings -> HashMap<&'input str, &'input str> = s:subheading ** "\n" { HashMap::from_iter(s) }
    subheading -> (&'input str, &'input str) = "===" title:title "===\n" innerbody:innerbody { (title, innerbody) }
    innerbody -> &'input str = .+ { match_str }
    "#);
    
    fn main() {
        let sample = "==Title1==\n===Subheading1===\nbody1\n===Subheading2===\nbody2\n==Title2==\n===SubheadingB===\nbodyB";
    
        println!("{:?}", layout::body(sample));
    }

And my output is:

    Ok({"Title1": {"Subheading1": "body1\n===Subheading2===\nbody2\n==Title2==\n===SubheadingB===\nbodyB"}})


I would like the output to be:

    Ok({"Title1": {"Subheading1": "body1", "Subheading2": "body2"}, "Title2": {"SubheadingB": "bodyB"}})

I tried to replace the `innerbody` definition with:

    innerbody -> &'input str = .+ &("\n==" / EOF) { match_str }
    EOF = !.

But it was the same result.

If this was a regex, I would say that the `+` in the `innerbody` rule is currently greedy and I want a non-greedy star. But I don't think that's a thing in PEGs.

Can you advise anyway to parse this input?

**Comment by kevinmehall** [comment]
Try something like

```
innerbody -> &'input str = (!"\n==" .)+ { match_str }
```

**Comment by rory** [comment]
Thanks! That worked!
