### ISSUE TITLE
[Info] If you use vim, I've made a syntax plugin for .rustpeg files.

### ISSUE THREAD

**Issue by treycordova** [kevinmehall/rust-peg#128]
_Feel free to close this "issue", but I'm not sure how else to mention it._

For all vim users: I've made a `.rustpeg` syntax [plugin](https://github.com/treycordova/rustpeg.vim).

If anyone has the time, it could use a few things:
- [ ] Building a small indent plugin. (Correct indentation when using `=` and `/`).
- [ ] Handling the embedded-in-Rust-with-multiline-string case.
- [ ] _Possibly_ reducing clashing colors. (I was looking at all of the syntax at once, which might explain my feelings.)

Other than that, enjoy.

**Comment by jonhoo** [comment]
:+1:
