### ISSUE TITLE
Expression that returns the slice of input that it matches, like peg.js $() or OMeta <>.

### ISSUE THREAD

**Issue by sandeep-datta** [kevinmehall/rust-peg#136]
Please try to compile the following ...

``` rust
#![feature(plugin)]
#![plugin(peg_syntax_ext)]

peg! modname(r#"
    #[pub]
    integer -> i64
        = WS* i:[0-9]+ WS*    { i.into_iter().collect::<String>().parse().unwrap() }

    WS = [ \t]*
"#);

fn main() {

}
```

Here are the errors that you will get ...

```
<peg>:1:17: 1:24 error: the trait bound `std::string::String: std::iter::FromIterator<()>` is not satisfied [E0277]
<peg>:1 { i.into_iter().collect::<String>().parse().unwrap() }
                        ^~~~~~~
main.rs:4:1: 10:5 note: in this expansion of peg! (defined in main.rs)
<peg>:1:17: 1:24 help: run `rustc --explain E0277` to see a detailed explanation
<peg>:1:17: 1:24 note: a collection of type `std::string::String` cannot be built from an iterator over elements of type `()`
```

Here is a work around ...

``` rust
peg! modname(r#"
    #[pub]
    integer -> i64
        = WS* i:digits WS*      { i.parse().unwrap() }

    digits -> String
        = [0-9]+            { match_str.to_string() }

    WS = [ \t]*
"#);
```

Though I actually prefer the workaround I would love it if we could have something like the ometa [consumed by](http://www.tinlizzie.org/ometa/ometa2.html) operator. So that we could do something like the following instead...

``` rust
peg! modname(r#"
    #[pub]
    integer -> i64
        = WS* i:<[0-9]+> WS*      { i.parse().unwrap() }

    WS = [ \t]*
"#);
```

**Comment by kevinmehall** [comment]
You could write this as 

```
    integer -> i64
        = WS* i:([0-9]+ { match_str.parse().unwrap()}) WS*  { i }
```

which also calls `parse` directly on the borrowed slice to avoid allocating a temporary string.

For that reason, literals don't return anything -- you want to parse a slice of the input string, not allocate a temporary list and append each character.

I do like the idea of a `<>` operator (or peg.js's `$()`) to bind a string slice as a replacement for the unhygenic `match_str`, though, so I'm turning this issue into that feature request.

**Comment by sandeep-datta** [comment]
I like this better than my work around! Thanks Kevin. 

You might want to highlight the following in the main README...
> Literals don't return anything -- you want to parse a slice of the input string, not allocate a temporary list and append each character.
