### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by y-ich** [kevinmehall/rust-peg#137]
Hi.

I compiled rust-peg but failed. Here is an error messge.

    Compiling peg v0.3.14 (file:///<path>/rust-peg)
    src/peg_syntax_ext.rs:5:14: 5:38 error: can't find crate for `syntax_pos` [E0463]
    src/peg_syntax_ext.rs:5 #[macro_use] extern crate syntax_pos;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error
    error: Could not compile `peg`.

My environment is,
OS: OS X 10.11.5
Rust: 1.11.0-nightly (ad7fe6521 2016-06-23)
Cargo: 0.12.0-nightly (50dad37 2016-06-21)

I googled and wonder that the feature rustc_private need to be added.
(Sorry that I don't know about rustc_private...)

**Comment by kevinmehall** [comment]
I [update](https://github.com/kevinmehall/rust-peg/commit/c7f4c49de45ca8490deaf1cdd4706421e31916cc) the library to follow the internal libsyntax API of rustc nightly.  You need a newer nightly or an older rust-peg.

**Comment by y-ich** [comment]
Thanks!
