### ISSUE TITLE
Release new version on crates.io

### ISSUE THREAD

**Issue by kazimuth** [kevinmehall/rust-peg#150]
I was getting an error whenever I used `pub` modifiers in my .rustpeg file, as explained in the README. This was fixed when I updated to the latest git version of this repository. Maybe make a new release on crates.io so that isn't necessary?

**Comment by kevinmehall** [comment]
:+1:, delayed to finish updating the docs, and then never got to it.

**Comment by kevinmehall** [comment]
Published 0.5.0.
