### ISSUE TITLE
Line comments go wrong

### ISSUE THREAD

**Issue by koba-e964** [kevinmehall/rust-peg#152]
Rules such as
```
op5 -> Op // %nonassoc "=" "<>" "<" ">" "<=" ">="
    = "=" { Op::Eq }
    / "<>" { Op::Ne }
    / "<=" { Op::Le }
    / ">=" { Op::Ge }
    / "<" { Op::Lt }
    / ">" { Op::Gt }
```
are not correctly compiled, because the line comment affects the rest of generated Rust code.
This phenomenon is observed in `peg v0.5.0`.

**Comment by kevinmehall** [comment]
Thanks for noticing and reporting this!
