### ISSUE TITLE
Warning when repetition range starts with 0

### ISSUE THREAD

**Issue by CodeSandwich** [kevinmehall/rust-peg#156]
Rustpeg generates code causing warnings during compilation if repetition count range starts with explicit 0.

Given Rustpeg code:
```
pub foo -> Vec<()>
    = "a"*<0,9>
```
There is a warning during compilation about useless `if` statement. The generated code (mind last line):
```
fn parse_foo<'input>(__input: &'input str, __state: &mut ParseState<'input>, __pos: usize) -> RuleResult<Vec<()>> {
    #![allow(non_snake_case, unused)] {
        let mut __repeat_pos = __pos;
        let mut repeat_value = vec!();
        loop {
            let __pos = __repeat_pos;
            if repeat_value.len() >= 9 { break }
            let step_res = slice_eq(__input, __state, __pos, "a");
            match step_res {
                Matched(newpos, value) => {
                    __repeat_pos = newpos;
                    repeat_value.push(value);
                },
                Failed => { break; }
            }
        }
        if repeat_value.len() >= 0 { Matched(__repeat_pos, repeat_value) } else { Failed }
        //                    ^ Pointless check, causes warnings
    }
}
```
Other than that the rule works fine.

This version works exactly same, but doesn't cause warning:
```
pub bar -> Vec<()>
    = "a"*<,9>
```

**Comment by kevinmehall** [comment]
I'm not sure there's a good way to prevent this kind of thing in general. The repeat counts allow arbitrary Rust expressions, so this is kind of like getting a compiler warning from your action code, except these code snippets are more closely tied to the code that rust-peg generates around them.

We could special-case "0", but what if you use `SOME_CONST`, which is defined to 0 somewhere else? Given that rust-peg is purely token-level manipulation, we can't go too far in trying to analyze your Rust code.

The Rust compiler will do the right thing and optimize it out, so we could just turn off warnings in the generated module. We already turn off a few, like unused code, that the generated code tends to trip a lot. But sometimes the warnings do find real issues with Rust snippets provided by the user.

**Comment by CodeSandwich** [comment]
You're right, special-casing 0 could be a useless complication. But I love the idea of adding `unused_comparisons` to the `#[allow()]` list. The warning noise from code out of programmers's reach is annoying, that's why you silenced `unused`. It causes exactly the same risks of programmer using some useless code in PEG, which will be ignored by the compiler anyway. I think it's a risk worth taking, `unused_comparison` is a rather rarely tripped warning, but analyzing generated code to track down a perfectly useless warning is frustrating. It's not caused by some overcomplicated edge case, it's one of the most basic PEG expressions.

**Comment by kevinmehall** [comment]
I'm going to call Rust's warning here correct, as the unused comparison is not generated if you don't set a lower bound: `"a"*<,9>`.
