### ISSUE TITLE
Add support for escaped match ranges

### ISSUE THREAD

**Issue by oberien** [kevinmehall/rust-peg#157]
Regexes allow specifying ranges in octal and hexadecimal like `[\200-\377]` and `[\x80-\xff]`. If I try to do this in rust-peg, I get the following error: `Error parsing language specification: error at 13:33: expected one of `\r`, `\u{2028}`, `\n`, `\r\n`, `\u{2029}`.

I ran into this issue while creating a dot parser. From the dot file specification:

> An ID is one of the following:
> * Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), not beginning with a digit;
> [...]
> --- <cite>[dot file specification](http://www.graphviz.org/doc/info/lang.html)</cite>

How can I match ranges which are encoding-dependend and may not have an ascii representation?

**Comment by kevinmehall** [comment]
The parse function takes a `&str`, and Rust requires `&str` to be valid UTF-8. The syntax for Unicode code points is the same `\u{2603}` as Rust.

If your input is not valid UTF-8, that's not currently supported. It wouldn't be too hard to add a mode where the parser takes a `&[u8]` instead and handles arbitrary bytes.

**Comment by dario23** [comment]
> If your input is not valid UTF-8, that's not currently supported. It wouldn't be too hard to add a mode where the parser takes a &[u8] instead and handles arbitrary bytes.

i'd be very happy to see that feature, is there anything i can do to make that happen? i don't really have a good overview of the codebase, but with some guidance i might accomplish a pull request for it (also, should i open a separate issue about that? feel free to edit/moderate my thread-highjacking ☺)

**Comment by dario23** [comment]
ok, after some code reading.. there are quite some places that are either `str` and `char` **or** `&[u8]` and `u8`, would you be willing to accept a PR making the type of thing configurable at compile-time with a feature flag? or rather via some annotation mechanism to the grammar (e.g. lalrpop does that).

**Comment by kevinmehall** [comment]
@dario23 I've actually just [started a major refactoring](https://github.com/kevinmehall/rust-peg/compare/revamp) for version 0.6 with this as one of the goals. I plan to write up an "RFC"-style issue to get feedback on these changes, but the gist is that all of the rust-peg operators could be redirected through a trait that could be implemented for `&[u8]` (or `&[Token]` or `proc_macro::TokenStream`, for that matter).

**Comment by kevinmehall** [comment]
[0.6.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) was released with support for `&[u8]` input and supports any matching syntax that you can use in a Rust `match` arm. [Example](https://github.com/kevinmehall/rust-peg/blob/master/tests/run-pass/bytes.rs).
