### ISSUE TITLE
Use the From<T> trait to simplify type matching requirements

### ISSUE THREAD

**Issue by sandeep-datta** [kevinmehall/rust-peg#161]
Could you please make the following (example) grammar work if suitable implementations of `From<i64>` and `From<f64>` are available?

```elm
pub expression -> Number
	= float / integer
	
integer -> i64
	= n:$([0-9]+) { n.parse().unwrap() }
	
float -> f64
	= n:$([0-9]+ "." [0-9]+) { n.parse().unwrap() }
```

Trying to compile this now will throw a type error since the two branches of the choice operator in the first rule are of different types. But wrapping the values returned by each child rule in From::from() will fix this problem if appropriate From implementations are available.

I believe this change has the potential to simplify a lot of grammars.

Refer: https://github.com/sd-rust/rust-peg-from for a complete (manually edited) working example.

To help you identify the required change here are the before and after snippets of the affected code ...

```rust
//BEFORE
fn __parse_expression<'input>(__input: &'input str,
                          __state: &mut ParseState<'input>,
                          __pos: usize)
                          -> RuleResult<Number> {# ! [ allow ( non_snake_case , unused ) ]{
        let __choice_res = __parse_float(__input, __state, __pos);
        match __choice_res {
            Matched(__pos, __value) => Matched(__pos, __value),
            Failed => __parse_integer(__input, __state, __pos),
        }
    }
}
```

```rust
//AFTER
fn __parse_expression<'input>(__input: &'input str,
                          __state: &mut ParseState<'input>,
                          __pos: usize)
                          -> RuleResult<Number> {# ! [ allow ( non_snake_case , unused ) ]{
        let __choice_res = __parse_float(__input, __state, __pos);
        match __choice_res {
            Matched(__pos, __value) => Matched(__pos, From::from(__value)),
            Failed => match __parse_integer(__input, __state, __pos) {
                Matched(__pos, __value) => Matched(__pos, From::from(__value)),
                Failed => Failed
            }
        }
    }
}
```

**Comment by sandeep-datta** [comment]
@kevinmehall could you please comment if this is a good thing to have? Would you entertain a PR implementing this?

**Comment by kevinmehall** [comment]
Do you have a more substantial grammar where this would be beneficial? In general, Rust avoids implicit conversions, and I think rust-peg should follow convention. Caling `.into()`, or in this case, constructing the enum variant explicitly is not that ugly.

One concern is that rust-peg generated code relies heavily on type inference, and `.into()` tends to unconstrain the type checker and require a lot of explicit annotations, potentially in generated code where the user can't add them.

**Comment by sandeep-datta** [comment]
Sorry for the late response. I do have a somewhat bigger grammar but it is more of the same stuff. If you don't find this convincing I doubt that will change your mind. Please close this issue if you are convinced it is not worth the trouble.
