### ISSUE TITLE
using cargo:rerun-if-changed makes it difficult to do other things in build script

### ISSUE THREAD

**Issue by polybuildr** [kevinmehall/rust-peg#163]
Since rust-peg [uses the rerun-if-changed feature of cargo](https://github.com/kevinmehall/rust-peg/blob/master/src/lib.rs#L43) for the rustpeg input file, the build script does not run if any of the other files changed, which is the [default behaviour otherwise](http://doc.crates.io/build-script.html#outputs-of-the-build-script).

This causes an inconvenience if the build script is also performing other tasks which would prefer having the default behaviour (if the list of files is too long to list out manually using rerun-if-changed too).

**Comment by polybuildr** [comment]
This could be controlled with some kind of configuration option, or maybe an environment variable? I would love to make a PR if you let me know what way to handle this you'd prefer.

**Comment by kevinmehall** [comment]
[0.6.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) is a procedural macro and no longer uses the build script.
