### ISSUE TITLE
Detect infinite loops / left recursion

### ISSUE THREAD

**Issue by canndrew** [kevinmehall/rust-peg#164]
It's very easy to accidentally write a parser that goes into an infinite loop. This could be detected by having the generated parse functions keep track of the stack and abort when the same rule gets invoked from the same position as an earlier invocation. It would save having to look through the trace and work out where the infinite loop is coming from.

**Comment by kevinmehall** [comment]
It should be possible to detect left-recursion statically. We should make this an error.
