### ISSUE TITLE
Translator throws away result of operator match in infix expression builder

### ISSUE THREAD

**Issue by collinwright** [kevinmehall/rust-peg#165]
When binding the result of an operator rule to a variable inside an infix expression builder, `translate.rs` currently just throws away the result of the match. From what I can tell reading through the source, keeping the result shouldn't break any other behavior, and allows for features such as a simplified version of Haskell's infix notation for function application (e.g. ``a `f` b``).

**Comment by kevinmehall** [comment]
This was supposed to exist, but a bug prevented it from working. Check out the test I added on 53932aa4181.
