### ISSUE TITLE
example of #infix with parentheses?

### ISSUE THREAD

**Issue by goodell** [kevinmehall/rust-peg#167]
It's likely that I'm just not good enough at identifying and eliminating left recursion in my grammar, but I can't seem to concoct a grammar based on [the example file](https://github.com/kevinmehall/rust-peg/blob/master/peg-tests/src/test_grammar.rustpeg) that supports infix operators (using `#infix<>`) and parentheses.  Would someone be willing to add an example of this?

Thanks!

**Comment by kevinmehall** [comment]
The parentheses would go in the infix parser's atom rule, instead of just numbers:

```
atom -> i64
	= "(" v:infix_arith ")" { v }
	/ number

pub infix_arith -> i64 = #infix<atom> {
	#L x "+" y { x + y }
	   x "-" y { x - y }
	#L x "*" y { x * y }
	   x "/" y { x / y }
	#R x "^" y { x.pow(y as u32) }
}
```

**Comment by goodell** [comment]
Excellent, this works for me.  I had tried a version of this but other aspects of the grammar (my buggy attempt at unary operators) caused me trouble so I had stopped pursuing this approach.  After some more fiddling, everything I've written a test for seems to work so far, including the unary operators.
