### ISSUE TITLE
provide a mechanism to automatically run rustfmt on generated parser code

### ISSUE THREAD

**Issue by goodell** [kevinmehall/rust-peg#168]
Occasionally it's useful to look at the generated code from rust-peg to debug an issue.  Unfortunately the generated code is difficult to read and usually needs a trip through `rustfmt`.  It would be a nice enhancement if I could run `cargo run --features peg/rustfmt` (or whatever more idiomatic Rust/Cargo would be) to cause the generated parser code to be formatted for me with `rustfmt` before feeding into any later steps in the build process.

I can try to investigate how to do this at some point, though I'm still pretty new to both Rust and rust-peg, so it would entail a lot of fumbling around for me along the way.  If @kevinmehall or anyone else knows how to just knock this out in 5 minutes in an idiomatic way then that would be awesome.

**Comment by kevinmehall** [comment]
If you `cargo install rust-peg` you can run `rust-peg src/x.rustpeg | rustfmt | less`. For debugging compile errors, I also sometimes `rustfmt` the output file in `target` and then `cargo build` again to see the error message in more readable form.

Rustfmt currently gives up on some of the super-long lines for complex parse rules. I think the ideal answer would be to make [quote](https://github.com/dtolnay/quote) at least make *some* attempt at reasonable formatting.

See also https://github.com/japaric/svd2rust/pull/72 (I'm not sure how much of that argument applies where we're less likely to check the output into git)

**Comment by goodell** [comment]
> If you `cargo install rust-peg` you can run `rust-peg src/x.rustpeg | rustfmt | less`.

That's a good trick, though it doesn't zoom my editor to the error line.

> For debugging compile errors, I also sometimes `rustfmt` the output file in target and then cargo build again to see the error message in more readable form.

Yes, this is what I've been doing so far.  It's certainly workable for occasional errors, but if you're still bumbling through Rust's type system and syntax (like I am) then IMO it seems clunkier than some option or `Cargo.toml` config that makes `rust-peg` handle the formatting.  Instead of `cargo build` I was running `cargo build || rustfmt target/**/calc.rs`.  That begs for some wrapper around it, but it seems like `cargo` is supposed to be the primary interface for building, testing, etc. in Rust World.

> Rustfmt gives up on some of the super-long lines for complex parse rules.

Yes, I had to `max_width = 1024` to `rustfmt.toml` for my grammar.

> I think the ideal answer would be to make quote at least make some attempt at reasonable formatting.

Oh cool, I didn't know about quote.  Yes, it seems unfortunate that it discards all your newlines, I suppose that's a side effect of implementing via macros?

> See also japaric/svd2rust#72 (I'm not sure how much of that argument applies where we're less likely to check the output into git)

A fair argument, though I think supporting running the `rustfmt` binary (rather than using rustfmt as a library) if it's installed seems like it sidesteps most of their issues.

To be clear, this is a minor issue, it just seems to me like it would be a nice enhancement for `rust-peg`.  Thanks for the suggestions.

**Comment by sandeep-datta** [comment]
I have submitted a pull request to address this problem: #185

**Comment by kevinmehall** [comment]
[0.6.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) is now a procedural macro, so the generated code is no longer written to disk, and the spans are preserved from your input source, leading to much better error messages that point at your source code instead of the generated file.
