### ISSUE TITLE
Runtime expression generation - desired approach?

### ISSUE THREAD

**Issue by ivanbakel** [kevinmehall/rust-peg#170]
I've got a use case of needing to parse a very user-forgiving whitespace language that unfortunately doesn't put any good rules on indentation, other than that it has to be consistent inside an indented block, and it can be any number of tabs or spaces otherwise, being decided by the first indent made.

To my mind, the immediate approach was to add support for runtime-evaluated parser rules which have access to the parser arguments, to allow for a local indentation tracker to be passed around and matched at will - but I thought it might be better to see how you'd approach this as well.

I have a crude runtime string-literal implementation working so far, but since the ideal would be to match `[\t ]+` for the first indent, I was hoping to allow the runtime full access to the range of possible expressions.

One idea would be to 
 * expose expression in the grammar i.e. `pub expression -> Expr` and then allow translate to be included in other grammars
 * supply runtime syntax - currently I'm using `={ <code> }`
 * crash hard when being passed invalid input

Thoughts?

**Comment by ivanbakel** [comment]
Although on closer inspection, exposing `expression` doesn't help at all with runtime processing because it's impossible to do anything with the generated code. Maybe just providing some helper methods for generating RuleResult()s e.g. from regex strings might be a good idea alongside the runtime notation.

**Comment by kevinmehall** [comment]
One approach I've seen for significant whitespace in other PEG parsers is [Pegasus's state variables](https://github.com/otac0n/Pegasus/wiki/Significant-Whitespace-Parsing).

If you're careful not to backtrack across indentation levels, you could get away with passing in something mutable as a grammar argument.

**Comment by ivanbakel** [comment]
I guess it could be done with

    indent = '\t'<{state.tabcount}> ' '<{state.spacecount}>

    indentation =
        indent<{state.indentation_level + 1}> #{state.indentation_level++} 
/ new_indent:[\t ]+ #{ state.tabcount = new_indent.num_of_tabs; state.spacecount = new_indent.num_of_spaces }

The only probem I see with that is the convoluted nature of it all, and possibly the lack of extension if I ever want to add another kind of tab character.

Also, how would rule failing be handled? Should the code check for a full match before running any blocks, or run as it tries and allow for an on-failure syntax like `#{ code }?{ more code}`?

**Comment by kevinmehall** [comment]
In [0.6](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0), you can accomplish this by defining your own input type and doing tokenization externally.
