### ISSUE TITLE
Can't build documentation

### ISSUE THREAD

**Issue by michaelmior** [kevinmehall/rust-peg#172]
When trying to build documentation for my crate which uses `peg` and `peg-syntax-ext`, I get the following error

```
warning: source code was requested to be rendered, but processing `<peg expansion>` had an error: No such file or directory (os error 2)
```

**Comment by kevinmehall** [comment]
Interesting find. It's just a warning, not an error; docs are still built, but it complains that it can't find the source code to format for the `[src]` link in the docs.

Looking at the [rustdoc source code](https://github.com/rust-lang/rust/blob/8b1271fcdd5b5958c76c43084e544d075d7d5dfd/src/librustdoc/html/render.rs#L888), we could make rustdoc ignore it by changing the fake filename to `<peg macros>`, but it might also make sense to patch rustdoc to ignore everything in angle brackets, as it's clearly not a real file.

**Comment by kevinmehall** [comment]
This is apparently a recent rustc regression: https://github.com/rust-lang/rust/issues/43371

**Comment by michaelmior** [comment]
Yes, it is just a warning, although documentation is *not* built in my case.

**Comment by kevinmehall** [comment]
No longer seeing this with the latest rustc nightly.
