### ISSUE TITLE
Document #[cache]

### ISSUE THREAD

**Issue by joliss** [kevinmehall/rust-peg#176]
What's the time complexity of the generated code? Is it potentially exponential, or always linear?

The Wikipedia page [mentions](https://en.wikipedia.org/wiki/Parsing_expression_grammar#Implementing_parsers_from_parsing_expression_grammars) that it's possible to generate linear-time "packrat parsers", so I'm wondering if that's what rust-peg is doing?

Perhaps this might be worth mentioning in the README as well.

**Comment by kevinmehall** [comment]
The generated code is a very straightforward translation of the grammar to a recursive decent parser. So indeed, you can write grammars that take time exponential in the number of characters. Idiomatic code tends not to be.

In cases where backtracking cannot be easily avoided, you can annotate rules with the `#[cache]` attribute, which provides packrat-style memoization on a rule-by-rule basis.

**Comment by berkus** [comment]
Didn't see mentions of `#[cache]` in the readme, is it described in more detail in the docs somewhere?
