### ISSUE TITLE
Support for rustdoc comments

### ISSUE THREAD

**Issue by oberien** [kevinmehall/rust-peg#178]
I'd like to write rustdoc comments above peg functions, which should be copied into the generated code. This allows documentation of these autogenerated functions without a need for a manual wrapper function.

Example:
```rust
/// What a rule
pub identity -> String
    = s:$(.*) { s.to_string() }
```

**Comment by kevinmehall** [comment]
Implemented on master in 6f9b5e8ccf7d9f52f35b33502726224ac46f1c9.
