### ISSUE TITLE
Stop parsing on pattern match

### ISSUE THREAD

**Issue by jocutajar** [kevinmehall/rust-peg#179]
Hi, I'd like to stop parsing the string input when a given pattern is matched. I'll give example for SMTP:

> helo abc
> mail from:<<me@example.com>>
> rcpt to:<<him@example.com>>
> data
> $%!...?^ö

The desire is that I could parse all the commands until including the data command. There is no point parsing further as there may be binary data there.

You could add a #quit instruction to terminate further processing:

pub cmd_data -> SmtpCommand
        = "data"i NL #quit
        { SmtpCommand::Data }

FYI: [the full SMTP grammar on github](https://github.com/BrightOpen/Samotop/blob/master/src/protocol/grammar.rustpeg). Btw, thanks a lot for PEG.

**Comment by kevinmehall** [comment]
Right now the generated wrapper function [checks that the match reaches the end of input](https://github.com/kevinmehall/rust-peg/blob/9796fab62afc7b300ec6e101b8544da9ca2bbe84/src/translate.rs#L440), and reports a `expected EOF` if it does not. This ensures that a top-level rule like `statement*` does not ignore statements that fail to match at the end of file. In your case, the `"data"` serves the same role. So we just need to add an optional attribute that disables that check.

**Comment by kevinmehall** [comment]
`#[no_eof]` was added in 0.7 - https://github.com/kevinmehall/rust-peg/pull/233

**Comment by Mingun** [comment]
For someone who looking for concrete solution:

```rust
peg::parser! {
  pub grammar stream() for str {
    pub rule event() -> T = ...;

    pub rule event_list() -> Vec<T> = event()*;

    #[no_eof] // Do not check for EOF after parsing rule
    pub rule event_iter() -> (T, usize)
      // Return position after parsing
      = r:event() p:position!() { (r, p) };
  }
}

let mut content = "...";
while !content.is_empty() {
  let (event, pos) = stream::event_iter(content)?;
  content = &content[pos..];
  // process event...
}
```
We add a new `*_iter` rule which calls our target rule and returns result together with the position after parsing, so we know where to start parsing of the next piece. It is equivalent to `event_list()` rule except that we get events one-by-one.
