### ISSUE TITLE
[Question] Can this crate produce rust code based on some grammar?

### ISSUE THREAD

**Issue by vityafx** [kevinmehall/rust-peg#182]
Am I correct thinking this crate can produce a rust code based on any grammar?

**Comment by rfdonnelly** [comment]
Yes.

For example, this grammar https://github.com/kevinmehall/rust-peg/blob/master/peg-tests/src/test_grammar.rustpeg#L4-L5 produces the function `consonants` which is called here: https://github.com/kevinmehall/rust-peg/blob/master/peg-tests/src/tests.rs#L13-L14

**Comment by vityafx** [comment]
Thanks.
