### ISSUE TITLE
Non greedy mode?

### ISSUE THREAD

**Issue by little-dude** [kevinmehall/rust-peg#186]
Hi,

I need to match comments delimited by `(*` and `*)`, for example:
```
(* comment *)

(*
    comment
*)

(* nested (* comment *) *)
```
Ignoring the nested comment case, I started with this:

```
pub comment -> ()
	= "(*" .* "*)"
```

But it seems that `peg` is greedy so `*)` will `.*` will match util the end of the string.

Is there a way to control `peg`'s greedy behavior? If not, how are such patterns usually matched using `peg`?

**Comment by little-dude** [comment]
Well, wikipedia actually had this very specific example in pseudo code, which translates to this in rust-peg:

```
pub comment_start -> ()
    = "(*"

pub comment_end -> ()
    = "*)"

pub comment_content -> ()
    = comment / (!comment_start !comment_end .)

pub comment -> usize
	= s:$(comment_start comment_content* comment_end)
```

Sorry for the noise.

**Comment by meme** [comment]
For anyone with this same problem in `peg` (= 0.6.0):

```rust
    rule comment_start() -> ()
        = "(*"
    
    rule comment_end() -> ()
        = "*)"
    
    rule comment_content() -> ()
        = comment()
        / (!comment_start() !comment_end() [_])
    
    rule comment() -> ()
        = (comment_start() comment_content()* comment_end())
```

(just getting started, not sure if this can be simplified)
