### ISSUE TITLE
how to reuse the return value for a given expression?

### ISSUE THREAD

**Issue by little-dude** [kevinmehall/rust-peg#187]
Hi,

I'm trying to parse strings for the [cool programming language](https://en.wikipedia.org/wiki/Cool_(programming_language)).

Valid strings are delimited by double quotes `"`.
A string may contain escaped newlines:
```
"This is \
valid"
```
Escaped characters are ignored (`"f\o\o"` is parsed as `foo` for example), except for `\b`, `\f`, `\t` and `\n`.

I came up with the following rules to perform the un-escaping and handle escaped newlines:
```
// replace
// "foo \
//      bar"
// by "foo bar"
linebreak -> &'static str
    = "\\\n" [ \t]*
    { " " }
// replace "\b" by an actual backspace
escaped_backspace -> &'static str
    = "\\b"
    { "\u{8}" }
// replace "\n" by an actual newline
escaped_newline -> &'static str
    = "\\n"
    { "\n" }
// replace "\f" by an actual formfeed
escaped_form_feed -> &'static str
    = "\\f"
    { "\u{12}" }
// replace "\t" by an actual horizontal tab
escaped_tab -> &'static str
    = "\\t"
    { "\t" }
// un-escape any character
escaped_char -> &'input str
    = "\\" s:$(.)
    { s }

string_content -> &'input str
    // This does not work
    = s:$(linebreak
      / escaped_backspace
      / escaped_tab
      / escaped_newline
      / escaped_form_feed
      / escaped_char
      // match any character except non-escaped newline and non-escaped double-quote
      / (!newline !"\"" .))
      { s }

pub string -> String
    = "\"" s:$(string_content*) "\""
    { s.into() }
```

Unfortunately, I don't get back the _parsed_ string, because `s:$(...)` returns the whole portion of the input that matched. In this case, I'd like something that returns what's returned by the expression that matches instead.

I this possible, or do I have to do the un-escaping myself? It seems similar to `a:e1 b:e2 c:e3 { rust }` except I'd need `a:e1 / b:e2 / c:e3 { rust }`.

**Comment by kevinmehall** [comment]
The result value of e1 / e2 / e3 is the result of whichever branch ended up matching. If you make each of your `escaped_`... rules as well as `string_content` return `char`, then  `s:string_content*` would be a `Vec<char>` that you could convert to a `String`. 

Check out how the the grammar for rust-peg's own syntax does string literals:
https://github.com/kevinmehall/rust-peg/blob/60355bd457b0f41082de224b70c4606b215698ad/src/grammar.rustpeg#L214

**Comment by little-dude** [comment]
Awesome, thank you, that worked!

```
// replace
// "foo \
//      bar"
// by "foo bar"
linebreak -> char
    = "\\\n" [ \t]*
    { ' ' }
// replace "\b" by an actual backspace
escaped_backspace -> char
    = "\\b"
    { '\u{8}' }
// replace "\n" by an actual newline
escaped_newline -> char
    = "\\n"
    { '\n' }
// replace "\f" by an actual formfeed
escaped_form_feed -> char
    = "\\f"
    { '\u{12}' }
// replace "\t" by an actual horizontal tab
escaped_tab -> char
    = "\\t"
    { '\t' }
// un-escape any character
escaped_char -> char
    = "\\" s:$(.)
    { s.chars().next().unwrap() }

non_escaped_char -> char
    = !newline !"\"" s:$(.)
    { s.chars().next().unwrap() }

string_content -> char
    = linebreak
      / escaped_backspace
      / escaped_tab
      / escaped_newline
      / escaped_form_feed
      / escaped_char
      // match any character except non-escaped newline and non-escaped double-quote
      / non_escaped_char
```


> The result value of e1 / e2 / e3 is the result of whichever branch ended up matching.

Except when the return type is not the same for all the expressions, in which case it default to `()`, right? If so, I think it would be nice to mention it in the README (I can make a PR for that).

Thanks for your help!

**Comment by kevinmehall** [comment]
> Except when the return type is not the same for all the expressions, in which case it default to (), right?

If the types aren't the same and you use the result value, you'll get a type error from rustc when compiling. If you don't use the result value of an expression at all, rust-peg replaces it with `()` so you can use `/` and not get a type error.
