### ISSUE TITLE
Add support for Rust 2018 keywords

### ISSUE THREAD

**Issue by doxxx** [kevinmehall/rust-peg#194]
In Rust 2018, there are a number of new keywords that are not accepted by `rust-peg`. For example, it is now recommended to use the `dyn` keyword to indicate trait objects, e.g. `Box<dyn MyTrait>`. However, the rust-peg syntax does not currently allow this in rule declarations. e.g. `myrule -> Box<dyn MyTrait>`. Another example is using `crate` (instead of `pub`) for symbols that must only be visible within the crate.

**Comment by ncalexan** [comment]
I would really like support for `pub(crate)`, but the [actual syntax is a little more general](https://doc.rust-lang.org/reference/visibility-and-privacy.html).  I looked at the `rust-peg` code and it's a little awkward to introduce the extension; @kevinmehall perhaps you could sketch the change to [`grammar.rustpeg`](https://github.com/kevinmehall/rust-peg/blob/ac20cfef124eb4d4d448bf35baab0dff0e2414e4/src/grammar.rustpeg#L24) and I can ripple some new `struct` to capture the richer visibility information through the rest of the code?

For the record, I don't see anything called "Rust 2018".  It does look like these were introduced in Rust 1.18, which might have coincided with the first release of 2018.

**Comment by doxxx** [comment]
Regarding Rust 2018: https://rust-lang-nursery.github.io/edition-guide/2018/index.html

**Comment by ncalexan** [comment]
> Regarding Rust 2018: https://rust-lang-nursery.github.io/edition-guide/2018/index.html

Oh, thanks!  I learned something today.
