### ISSUE TITLE
Is it possible to define a rule which returns an enum?

### ISSUE THREAD

**Issue by WarpspeedSCP** [kevinmehall/rust-peg#199]
I would like to use an enum type to distinguish between three types of tokens (labels, string literals and integers). But, it seems like I can't directly use the alternation syntax to process the three types - 

```
pub arg -> util::arg = label / str_lit / hex_lit {
    . // How do I know which parser function was called?
    .
    .
}
```

`util::arg`

```
pub enum arg {
    Label(String),
    StrLit(String),
    IntLit(i32)
}
```

Is there a way to change the output depending on the source of the input?

**Comment by kevinmehall** [comment]
You can put action code on each of the arms of the `/`:

```
pub arg -> util::arg
  = l:label { util::arg::Label(l) }
  / s:str_lit { util::arg::StrLit(s) }
  / i:hex_lit { util::arg::IntLit(i) }
```
