### ISSUE TITLE
With `edition = "2018"`, get "expected expression, found reserved keyword `try`"

### ISSUE THREAD

**Issue by emk** [kevinmehall/rust-peg#200]
Thank you for maintaining `rust-peg`! It's a great parser generator.

To reproduce: Using beta Rust, add `edition = "2018"` to the `[package]` section of the `Cargo.toml` file.

What happens: I get the error "expected expression, found reserved keyword `try`". This is caused by `try !` in the source code, where there's a space between the `try` and the `!` in the `try!` expression.

What should happen: The generated code should be compatible with Rust 2018 for use in crates declaring `edition = "2018"`, which is the default in 1.30.0-beta releases of Rust.

**Comment by emk** [comment]
Thank you! I would definitely be interested in a patch release if you have the spare time to make one. If you'd like, I could try to backport the patch to 0.5 and send a PR.

If it's all too much bother, I can avoid migrating my `rust-peg`-using crates Rust 2018 until rust-peg 0.6 is out, of course. :-) I use it for all kinds of projects, and I always enjoy it.

**Comment by kevinmehall** [comment]
Released 0.5.7.

**Comment by emk** [comment]
Thank you very much! We've updated our code at work to Rust 2018 and this helped nicely with on of our internal modules that did a little bit of parsing.
