### ISSUE TITLE
Recursive Template Rules Overflow Stack

### ISSUE THREAD

**Issue by JDemler** [kevinmehall/rust-peg#202]
Just wanted to write a parsing rule for delimited lists:

```peg
delimited_list<T, D>
  = nested:delim_list_nested<T, D>  { nested }
  / last:T { DelimitedList::new(last) }

delim_list_nested<T, D> 
  = current:T delim:D next:delimited_list<T, D> { next.add_segment(current, delim) }
```

Unsurprisingly, as templates are always inlined, this overflows the stack during compilation.
I'm not sure how this could be fixed conceptually. But maybe you have an idea?

Love this library btw. Thanks for creating it!

**Comment by Mingun** [comment]
> I'm not sure how this could be fixed conceptually.

PEG formalism already has the concept of the sequence why instead of it to use a recursion? It was necessary for original BNF grammars which had no `repeat` primitive.

I do not know specifically this PEG library therefore implement actions, all the same it will be required to use other API:
```rust
delimited_list<T, D> = first:T last:(delim:D elem:T)*
// or, if trailing delimiter is allowed
delimited_list<T, D> = (elem:T delim:D)* last:T?
```

**Comment by JDemler** [comment]
... thanks, that's much better!

**Comment by kevinmehall** [comment]
[0.6.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) replaces template rules with [rule arguments](https://github.com/kevinmehall/rust-peg/blob/master/tests/run-pass/rule_args.rs), which *might* be able to handle this, but using the `*` operator is still a better approach.
