### ISSUE TITLE
Beginner help please

### ISSUE THREAD

**Issue by chrismatheson** [kevinmehall/rust-peg#205]
Hi,

im experimenting with this library to try and capture a tree of statements from js BDD style code'

i.e. 
```
describe('EditCenterForm', function () {it('should be able to create US centers', async function () {});});
```

would contain a 
```
vec![Describe {
  val: "EditCenterForm",
  children: vec![It { val: "should be able to create US centers"}]
}]
```

my main stumbling block (i think) is that i can't figure out a way to express, ignore all chars until "describe(" 

so far ive got 

```
parser! {
  grammar spec_parser() for str {
    rule char() -> String
      = c:$(['a'..='z' | 'A'..='Z' | ' ']+) { c.to_string() }

    rule it() -> It
      = "describe('" val:char() "'," {
           It {
                value: "blah".to_owned()
           }
       }

    rule code() -> ()
      = [_] { () }

    pub rule spec() -> Vec<It> = precedence!{
        d:code()* { vec!() }
    }
  }
}```

but i think I'm not understanding something about PEG's in general. Any help / pointing to further reading would be appreciated.

**Comment by kevinmehall** [comment]
A PEG expression to ignore all chars until `describe(` would be `(!"describe(" [_])*` -- `!"describe("` accepts without consuming characters if the remaining text doesn't start with `describe(`, and then `[_]` consumes one character.

However, I don't think that's what you really want for what you're trying to do. Imagine cases where that string is found within a JS string literal, comment, or even a call to `otherdescribe()`. Your parser would have to understand a subset of JS, not just perform a string match, to be able to distinguish these cases. While you could write a JS parser or tokenizer with rust-peg, you're probably better off using an existing one like the [ressa](https://crates.io/crates/ressa) crate.

**Comment by chrismatheson** [comment]
Thanks for the quick reply! yeah i had thought of going down the "full js" parsing, however my intention is to make a "good enough" not perfect version just now, and parsing multiple languages will definitely be a key feature.

ill give this a go tonight :) thanks a ton
