### ISSUE TITLE
Cargo build

### ISSUE THREAD

**Issue by tathanhdinh** [kevinmehall/rust-peg#206]
Hello all,

Sorry for this stupid question, there was `peg::cargo_build("some_grammar_file")` to generate the parser, but it seems to be removed in `0.6.0`. How can get the similar feature in this version?

Thanks in advance.

**Comment by kevinmehall** [comment]
In 0.6.0, you use the `peg::parser!{}` macro in a `.rs` file, and no longer need a build script or a separate `.rustpeg` file. See the "Upgrade from 0.5.x" section of the release notes: https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0

**Comment by tathanhdinh** [comment]
Thank you and sorry for did not reading the release notes carefully. I will try this new method.
