### ISSUE TITLE
Matching strings

### ISSUE THREAD

**Issue by chronium** [kevinmehall/rust-peg#208]
Hello.

How would I go about parsing string literals?
I tried using `[_]` but it does not seem to work.

Here is the rule I tested:
```rust
rule string_literal() -> ParseTree
    = "\"" s:$([_]*) "\"" { ParseTree::StringLiteral(s.to_string()) }
```

**Comment by kevinmehall** [comment]
Unlike in regular expressions, PEG doesn't backtrack when a rule succeeds. In this case, the `[_]*` matches all the way to end of input and then the final `"\""` fails.

To prevent this, you need to exclude the quote character inside the string. You can do this with `!("\"")`, which matches only if the next character is not a quote, without consuming it. You can similarly exclude `\` and handle it separately for escape sequences. See https://github.com/signalspec/signalspec/blob/ea462b572b427bf0384fed23e283fc44f54767a9/src/syntax/grammar.rs#L177-L184 for an example.

**Comment by piegamesde** [comment]
Please add an idiomatic example to the documentation. In my case, I wanted to match the rest of the line, and `$(!"\n" c:$([_])+)` looks like it will do.

**Comment by kevinmehall** [comment]
@piegamesde If I understand what you're trying to do correctly, `s:$((!"\n" [_])*)` may be a simpler and more performant alternative -- capture the whole match as a string slice directly rather than collecting each character to a `Vec<char>` and back.
