### ISSUE TITLE
Help wanted: ungreddy parse

### ISSUE THREAD

**Issue by youlinxiaozhu** [kevinmehall/rust-peg#211]
I  can  parse expression like `snake_case__type` using regex `([\w]+)__(\w+)`, but I don't know how to parse use peg, because peg is always greedy.

**Comment by kevinmehall** [comment]
You can use negative lookahead for this. `(!"__" [_])+` matches any sequence of characters up until two adjacent underscores.

**Comment by youlinxiaozhu** [comment]
@kevinmehall Thank you for your help.
