### ISSUE TITLE
Strange compiler errors when doing super simple example

### ISSUE THREAD

**Issue by nshcat** [kevinmehall/rust-peg#214]
Hello,
when using this crate with the following super simple grammar:

```
parser!{
	grammar test_parser() for str {
		pub rule number() -> f64
			= n:$(['0'..='9']+) { n.parse().unwrap() }
	}
}
```
I get a weird error:

```
error[E0107]: wrong number of type arguments: expected 0, found 2
   --> src/main.rs:637:24
    |
635 | / parser!{
636 | |     grammar test_parser() for str {
637 | |         pub rule number() -> f64
    | |                              ^^^ unexpected type argument
638 | |             = n:$(['0'..='9']+) { n.parse().unwrap() }
...   |
651 | |     }
652 | | }
    | |_^ unexpected type argument
```
Interestingly, if I remove the `pub` specifier from the rule it works, but then the rule is no longer useable. Am I doing something wrong?

Thanks in advance.

**Comment by kevinmehall** [comment]
That's weird. Can you share a more complete example? I was unable to reproduce it with Rust 1.39 and `peg` 0.6 by putting that in a file with `use peg::parser;` on top.

I suspect something in your module is getting pulled into the peg-generated module by the `use super::*` it inserts, and shadowing something that the generated code needs. Rust macros aren't fully hygienic yet, so we have to be careful to use only fully qualified names in the generated code to avoid those conflicts. It's possible that I missed one.

**Comment by kevinmehall** [comment]
Do you have a `struct Result;` in your module? I was able to reproduce your error by adding that. It's an easy fix, but I'm going through to make sure there aren't others.

In the meantime, a workaround is to put the `parser!{}` invocation in its own `mod{ }` or file so that's not in scope.

**Comment by nshcat** [comment]
Thank you very much, it was my own Result type that made things go wrong!
