### ISSUE TITLE
Expressions in parentheses with `!precedence` macro

### ISSUE THREAD

**Issue by nusskuchenx86** [kevinmehall/rust-peg#215]
Hi! Awesome crate you made here :)

I'm using the `!precedence` macro to parse an arithmetic expression and build an AST:

```
rule arith_expr() -> ArithmeticExpression = precedence!{
        l:(@) padding() "+" padding() r:@ { ArithmeticExpression::Add(boxed(l), boxed(r)) }
	l:(@) padding() "-" padding() r:@ { ArithmeticExpression::Sub(boxed(l), boxed(r)) }
	--
	l:(@) padding() "*" padding() r:@ { ArithmeticExpression::Mul(boxed(l), boxed(r)) }
	l:(@) padding() "/" padding() r:@ { ArithmeticExpression::Div(boxed(l), boxed(r)) }
	--
	l:@ padding() "^"  padding()r:(@) { ArithmeticExpression::Pow(boxed(l), boxed(r)) }
	--
	"-" r:(@) { ArithmeticExpression::Neg(boxed(r)) }
	--
	n:number() { ArithmeticExpression::Const(n) }
	p:parameter_name() { ArithmeticExpression::Param(p) }
}
```

This works fine and is super convenient, but I'm wondering if there is a canon approach of introducing expressions wrapped in parentheses with this macro?
For example, according to precedence rules, the expression `x + 3 * y` would be parsed to `(x + (3 * y))`, so I want to give the user a way to use parentheses, like in the expression `(x + 3) * y`, which would be parsed to `(x + 3) * y`. Is this possible?

Thanks and, again, super awesome and easy to learn library!

**Comment by kevinmehall** [comment]
Parentheses reset the precedence level, so instead of using `@`, just recurse into the `arith_expr` rule. A rule without `@` is treated as an atom, so add something like `"(" e:arith_expr() ")" { e }` at the bottom precedence level.
