### ISSUE TITLE
Generic input lifetime for grammar

### ISSUE THREAD

**Issue by PurpleMyst** [kevinmehall/rust-peg#220]
Hi, I have a type `Tokens<'code>` in my code that wants to use `rust-peg`'s `parser!` proc-macro, however I can't figure out how to do something like the following:

```rust
peg::parser! {
    grammar feeny<'a>() for Tokens<'a> {
        // snip
    }
}
```

Is there a way to do this?

**Comment by kevinmehall** [comment]
Not currently. There is support for type and lifetime parameters on rules, but not on the grammar as a whole.

Implementing it would take adding `rust_ty_params()` to the `peg_grammar` rule in [the meta-grammar](https://github.com/kevinmehall/rust-peg/blob/master/peg-macros/grammar.rustpeg), and then threading that through to the right places in the output.

**Comment by PurpleMyst** [comment]
Is this particularly difficult? I'd be willing to do it with a small bit of mentoring
