### ISSUE TITLE
Question: rule interception

### ISSUE THREAD

**Issue by CertainLach** [kevinmehall/rust-peg#231]
Hello!
I am writing a json template language interpreter: jsonnet, and use this library as source code parser:
https://github.com/CertainLach/jsonnet-rs/blob/master/crates/jsonnet-parser/src/lib.rs#L19

There are multiline strings in this language with this syntax:
```jsonnet
local a = |||
     text # This line should start with n+m (Where m>=1)  spaces
          text2 # This line should start with n+m spaces plus any amount of spaces after it
   ||| # This line should start with n spaces
```

I can't find a way to translate this pattern to PEG syntax, so i should write parser myself

The problem is: how can i start parsing input myself at some point of peg parser execution?

**Comment by kevinmehall** [comment]
For languages with significant whitespace, my recommendation has typically been to use an external lexer, but in this case it looks like this type of string literal is only one small part of the language and the rest of it is more easily parsed.

I've wanted to add an expression type to rust-peg in which you embed a code block that gets passed the input and current position, and returns a new position and return value, or an error. This is basically the interface to expression expansions internally, so it would be trivial to implement, but I have yet to come up with a decent syntax for it.

What does already exist but is undocumented is the `##method()` syntax. This expands to call `input.method(pos)` which returns `RuleResult`. As an example, the peg meta-grammar [uses it](https://github.com/kevinmehall/rust-peg/blob/master/peg-macros/grammar.rustpeg#L137) to call into [a function here](https://github.com/kevinmehall/rust-peg/blob/6dc303342ecb2c7ab43c08861f9351454a366f2d/peg-macros/tokens.rs#L58). You can define and implement a trait for `str`, and `use` the trait in the grammar, to extend `str` with a method.

**Comment by kevinmehall** [comment]
Actually, you can probably implement that multiline string syntax in peg directly if I'm understanding it correctly. Something like:

```
rule rest_of_line() -> &'input str = s:$((!['\n'][_])* ['\n']) {s}
rule string_block() -> String 
    = "|||" rest_of_line() 
        prefix:[' ']* first_line:rest_of_line()
        lines:([' ']*<{ prefix.len() }> s:rest_of_line() { s })*
        [' ']* "|||"
        { let mut l = first_line.to_string(); l.extend(lines); l }
```

**Comment by CertainLach** [comment]
I already tried to implement it via peg, but i didn't know about possibility to put expressions  in repeat specifiers, so i dirty implemented this for fixed abount of spaces:
![image](https://user-images.githubusercontent.com/6235312/84598568-1ede7400-ae85-11ea-8491-093ee278b249.png)

Now i have successfully rewritten this as:
![image](https://user-images.githubusercontent.com/6235312/84598758-7df0b880-ae86-11ea-879d-71506e230358.png)

Thanks!
