### ISSUE TITLE
How to match and return a one char?

### ISSUE THREAD

**Issue by Mingun** [kevinmehall/rust-peg#234]
I'm tries to write parser, that will return one matched char and I do not see, how I can achieve that in simple way:
```rust
rule quotedChar() -> char = ['a'|'b'|'t'|'n'|'v'|'f'|'r'|'e'|'\''|'"'|'\\'];
rule quotedChar() -> char = ch:['a'|'b'|'t'|'n'|'v'|'f'|'r'|'e'|'\''|'"'|'\\'] { ch };
```
Both infers return type as `()`. For now I found only such solution:
```rust
rule quotedChar() -> char = ch:$['a'|'b'|'t'|'n'|'v'|'f'|'r'|'e'|'\''|'"'|'\\'] { ch.chars().next().unwrap() };
```
Is there any better solution?

**Comment by kevinmehall** [comment]
I think that's the best that exists right now. I don't remember the reason why `[]` doesn't return a reference to the matched item from the input. I'll leave this open to see if that can be added or document the reason why not.

**Comment by wlott** [comment]
> ```rust
> ch.chars().next().unwrap()
> ```
> 
> Is there any better solution?

I personally have found:
```rust
char::from_str(s).unwrap()
```
to read slightly better.  Granted, it will panic if the matched string isn't one character while the `.chars().unwrap()` will only panic if there are zero characters in the string.  That may be a good thing or a bad thing depending on your views towards fault tolerance vs rigorous consistency checking.
