### ISSUE TITLE
Output trace with indentation

### ISSUE THREAD

**Issue by Mingun** [kevinmehall/rust-peg#236]
Currently `peg/trace` output is hard to understand, because it shows matches only for rules, not for grammar atoms (such as "literals" and [character_classes]), especially for recursive rules.

Indented output where indentation increases after trying match rule and decreases after match/fail would be great addition.

**Comment by kevinmehall** [comment]
You might want to try https://github.com/fasterthanlime/pegviz

**Comment by Mingun** [comment]
Because using suggested utility solves problems with debugging grammar, I close this
