### ISSUE TITLE
How to match against an input to rule (non-literal) string?

### ISSUE THREAD

**Issue by davidOSUL** [kevinmehall/rust-peg#237]
e.g:
For matching against literal strings we can do:
```rust
pub rule matchIt() = "matchesThisLiteralString"
```

but is there anyway to do something like:
```rust
pub rule matchIt(x: &str)  = <matches if equals x> 
```

**Comment by kevinmehall** [comment]
`##parse_string_literal(x)` -- [Example from the test suite](https://github.com/kevinmehall/rust-peg/blob/08c74792acbb3f1959eaee87ac314eff11cf601c/tests/run-pass/rule_args.rs#L15)

The `##` syntax is a semi-undocumented feature that calls a method on the input string, and it passes the same arguments as the [ParseLiteral::parse_string_literal](https://docs.rs/peg/0.6.3/peg/trait.ParseLiteral.html#tymethod.parse_string_literal) method expects.
