### ISSUE TITLE
Dynamic counts for repetition indexes

### ISSUE THREAD

**Issue by Mingun** [kevinmehall/rust-peg#239]
I can not find, how to read usual "pascal string": length and some content of this length. In my fork of pegjs [I implement](https://github.com/Mingun/pegjs#expression-count-expression-minmax-expression-count-delimiter-expression-expression-minmax-delimiter-expression) following solution and I would like to see that rust-peg supports it too:
```
// using previously parsed `len` as count in range syntax
rule pascal_string() -> len:integer() content:$([_]*<len>) { content };
```

**Comment by kevinmehall** [comment]
That's [supported](https://docs.rs/peg/0.6.3/peg/#repeat-ranges) using the `expr*<{len}>` syntax.

**Comment by Mingun** [comment]
It's weird how I missed it. May be use the list at this location in the documentation to make the list of available formats more explicit?
