### ISSUE TITLE
How do "_" rules work?

### ISSUE THREAD

**Issue by piegamesde** [kevinmehall/rust-peg#243]
I don't understand this rule:

> _ or __ or ___ - Rule (underscore): As a special case, rule names consisting of underscores are invoked without parentheses. These are conventionally used to match whitespace between tokens.

If I read the definition correctly, I need to call my rule `_` and then it will work?

```rust
rule _ = skip_whitespace()
```

however gives me:

```
error: expected one of "(", "<"
  --> src/placement.rs:43:16
   |
43 |         rule _ = skip_whitespace()
   |                ^

error: aborting due to previous error
```

**Comment by mdenchev** [comment]
You only omit the `()` when invoking, not when defining. So it would be:
```rule _() = skip_whitespace()```

**Comment by piegamesde** [comment]
Yeah, that makes sense. Maybe add that line somewhere as an example in to the documentation, please?

**Comment by kevinmehall** [comment]
We should probably just make it accept the more obvious `rule _ = `syntax here.
