### ISSUE TITLE
Should README contain ++ in the delimited repeats section?

### ISSUE THREAD

**Issue by CGMossa** [kevinmehall/rust-peg#250]
While reading examples of peg-grammars, I found this:

```rust
    pub rule keyvals() -> HashMap<i64, i64>
        = kvs:keyval() ++ "\n" { //<-- this line
            kvs.iter().cloned().collect::<HashMap<i64, i64>>()
        }
```

To me this is the same as:

```markdown
expression ** delim - Delimited repeat: match zero or more repetitions of expression delimited with delim and return the results as a Vec.
```

From the `README`, but it is not noted here.

**Comment by kevinmehall** [comment]
Added, thanks.

(I do wonder whether `++` doesn't pull its weight, but it's implemented, so it might as well be documented. It may be confusing because `++` is used as a concatenation operator in other languages,)

**Comment by CGMossa** [comment]
Thank you so much for the positive feedback on my small suggestion.
