### ISSUE TITLE
Grammar input type requires a ".len()" method

### ISSUE THREAD

**Issue by adrianwn** [kevinmehall/rust-peg#251]
The generated parser code calls the `len()` method on the grammar input, but the `Parse` trait doesn't contain such a function. This limits the types that can be used as input for the parser. I can think of two ways to fix this:

1. Add a `len()` function to the `Parse` trait.
2. I believe there are only two places where `len()` is called on the input, and both are conditions in the form of `__pos == __input.len()`. So instead of adding a `len()` trait function, I suggest `fn is_eof(&self, p: usize) -> bool`, which can easily be implemented for any type that already has a `len()` method.

What do you think? I'd be happy to provide a pull request, if desired.

**Comment by kevinmehall** [comment]
Yeah, all the methods called on input should go through the traits -- thanks for pointing that out.

Option 2 sounds good to me.
