### ISSUE TITLE
Add utility function for nicer parse error messages

### ISSUE THREAD

**Issue by Dema** [kevinmehall/rust-peg#253]
I think it would be great to have something like this in peg
```rust
fn pretty_print_parse_error<Input: std::fmt::Display>(
    input: Input,
    e: peg::error::ParseError<peg::str::LineCol>,
) -> String {
    chic::Error::new("")
        .error(
            e.location.line,
            e.location.offset,
            e.location.offset + 1,
            &input,
            format!("Expected: {}", e.expected),
        )
        .to_string()
}
```
This gives really nice and helpful error messages!
```
Parse Error: error
  |
1 | ecl:hzl cid:279 pid:192cm
  |                        ^ Expected: '0' ..= '9'
2 | hcl:#1f7352 iyr:2014 hgt:150cm eyr:2021
3 | byr:2002
  |
```
I'm a rust newbie, so I think this has some room for improvement, but it really helps with debugging grammar

**Comment by kevinmehall** [comment]
`chic` looks nice as a simple option. There are several other similar libraries like [annotate-snippets](https://github.com/rust-lang/annotate-snippets-rs), [codespan-reporting](https://github.com/brendanzab/codespan) and my own (but semi-unmaintained) [codemap-diagnostic](https://github.com/kevinmehall/codemap-diagnostic/). I don't think it's in scope for a parser library to be closely coupled to any one of them, but links to these and example code like yours seem like a good idea.

**Comment by Dema** [comment]
I didn't know that there's so many of them! rust community is amazing! :)

Maybe it makes sense to add some examples of using them into peg docs? I'm going through an https://fasterthanli.me/series/advent-of-code-2020 series, and they use peg for parsing, but debugging grammar without this kind of diagnostic is really hard.
