### ISSUE TITLE
How to reliably parse a number?

### ISSUE THREAD

**Issue by bemyak** [kevinmehall/rust-peg#255]
I want to parse a user input, one part of which should be a number (`u16`), so the rule looks like this:
```
rule num() -> u16
  = num:$(['0'..='9']+) { num.parse().unwrap() }
```

The problem here is that if the input number is larger then u16, the code panics on `unwrap()`.

One way to avoid this would be to return a `Result`, but then it makes it really difficult to reuse this rule, and outputs of all other rules must be `Result`s as well, which is a really troublesome.

The other way I see is to [catch the panic](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html), but this also feels wrong.

What I would like to have here is a way to tell Peg that the rule doesn't match **from inside of it**. For example, in addition to `rule` have a special `try_rule` that must return a result and if it is an error, treat that rule as a non-match.

Is this somehow possible? Maybe there are other solutions that I don't see?

**Comment by kevinmehall** [comment]
You're looking for the `{? ...}` ["conditional action"](https://docs.rs/peg/0.6.3/peg/#combining) syntax. 

```rust
rule num() -> u16
  = num:$(['0'..='9']+) {? num.parse().or(Err("16-bit integer")) }
```

**Comment by bemyak** [comment]
Indeed, thank you so much!
