### ISSUE TITLE
Support for inverted pattern

### ISSUE THREAD

**Issue by 2000jedi** [kevinmehall/rust-peg#256]
I just noticed that the inverted pattern `[^ ]` is not available. 
The test case `pattern.rs` cannot compile with the following error output:
> expected pattern, found `^`

**Comment by kevinmehall** [comment]
This was added in #245 and will be released in 0.7 soon.

**Comment by kevinmehall** [comment]
Released [0.7.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.7.0)
