### ISSUE TITLE
Preprocess matched string with rule before parsing it with another rule

### ISSUE THREAD

**Issue by untitaker** [kevinmehall/rust-peg#26]
I have a parser that can split a file like this into a hashmap:

```
FOO:foo
BAR:bar
BAZ:baz
```

However, some values span over multiple lines when the continuing lines start
with a single space, the following would be equivalent:

```
FOO:
 bar
BAR:bar
BAZ:b
 az
```

The problem is that the linebreak can happen anywhere, not just in the value.
Therefore i'd like to match the line with a rule similar to this:

```
continuation = eol whitespace
continuations -> &str
    = x:[a-zA-Z:] ++ continuation {
    let mut rv = "";
    for p in x.into_iter() {
        rv += p;
    };
    rv
}
```

And feed the returned value into my previous parser.

The progress of this can be viewed at https://github.com/untitaker/rust-vobject/pull/1

**Comment by kevinmehall** [comment]
[0.6.0](https://github.com/kevinmehall/rust-peg/releases/tag/0.6.0) adds support for defining your own input types via traits, which you could use to preprocess input like this.
