### ISSUE TITLE
Delimited repeat expression should be in parenthesis (or not?)

### ISSUE THREAD

**Issue by xolve** [kevinmehall/rust-peg#260]
This is about example given on introduction [Parse a comma-separated list of numbers surrounded by brackets into a Vec<u32>](https://docs.rs/peg/0.7.0/peg/#example).

The following is the rule to match the list:
```
    pub rule list() -> Vec<u32>
      = "[" l:number() ** "," "]" { l }
```

Here variable name `l` matches with `number() ** ","`. It might be my unfamiliarity with such grammar rules, I was confused that `l` is only bound to `number()` because of whitespace after the latter.

I feel that putting parenthesis is more apt: `l:(number() ** ",")`.

**Comment by kevinmehall** [comment]
The `**` binds more tightly than the `:` labels, so these are equivalent. I see how this could be confusing though, especially as the whitespace is insignificant. I'll update the examples for clarity. Thanks for the suggestion!
