### ISSUE TITLE
Allow scoping in rule arguments

### ISSUE THREAD

**Issue by Ondraceq** [kevinmehall/rust-peg#261]
Hi,
I'm trying to use parametrized rules with my own enum type (&[T]).
Problem is that when using parametrized rules, I cannot use scoping. I have managed to do a workaround, but it's really not ideal.
Here is the code with the workaround - and with what I think would be better way to be able to write it.

```
#[derive(Debug, Clone, PartialEq)]
pub enum MyEnum {
    Value,
}

const ENUM_VALUE: MyEnum = MyEnum::Value;

peg::parser! {
    grammar my_parser() for [MyEnum] {
        rule single(val:MyEnum) -> MyEnum = [v if v == val] { v }
        // pub rule value() -> MyEnum = single(MyEnum::Value) // error
        pub rule value() -> MyEnum = single(ENUM_VALUE)
    }
}
```

I'm using the "0.7.0" version from crates.io

**Comment by kevinmehall** [comment]
Thanks for pointing that out. As a better workaround, it should work if you wrap it in an extra set of parentheses `single((MyEnum::Value))`.

The [`rule_arg()` rule in the meta-grammar](https://github.com/kevinmehall/rust-peg/blob/d052bc60e4536147f342e4b85f462dd45c4ad286/peg-macros/grammar.rustpeg#L131) needs to be expanded to better cover Rust expressions. Right now it only accepts literals, variable names, and anything in parentheses.

**Comment by Ondraceq** [comment]
Thank you - I didn't know that the parenthesis will work.
This makes this issue low priority - maybe just mention it somewhere in the docs/examples.
