### ISSUE TITLE
Handling multiple parse errors

### ISSUE THREAD

**Issue by neunenak** [kevinmehall/rust-peg#274]
Right now, rust-peg will fail the first time it encounters any parse error. It would be useful if it could recover from an error, continue parsing (while potentially encountering additional errors), and then return all encountered errors when all of the input is consumed. 

There's a [recent academic paper](https://arxiv.org/pdf/1806.11150.pdf) that describes a strategy for extending the PEG formalism to support this.

**Comment by kevinmehall** [comment]
I had started writing a long answer to another recent question about supporting LSP, and this is a subset of that, so I'll combine this into the same discussion thread: https://github.com/kevinmehall/rust-peg/discussions/276
