### ISSUE TITLE
Compilation failure with `--features peg/trace`

### ISSUE THREAD

**Issue by JohnEmhoff** [kevinmehall/rust-peg#277]
I get this error when trying to run with `cargo run --features peg/trace`:

```
error[E0425]: cannot find value `min_prec` in this scope
   --> src/ast.rs:221:1
    |
221 | / peg::parser! {
222 | |     pub grammar parser() for [Token] {
223 | |         rule ident() -> String=
224 | |             [Token::Ident(s)] { s } / expected!("identifier")
...   |
356 | |
357 | | }
    | |_^ not found in this scope
```

I stared at the code for a bit to try to help diagnose but I don't think my rust macro-fu is anywhere near up to the task, unfortunately.

**Comment by kevinmehall** [comment]
Thanks for reporting! Added testing with `trace` in GitHub Actions and fixed another regression there that had been added since 0.7.

**Comment by JohnEmhoff** [comment]
Thanks for the quick turnaround! And thanks for the library too, it's great.
