### ISSUE TITLE
Does this compile to WASM?

### ISSUE THREAD

**Issue by aunyks** [kevinmehall/rust-peg#280]
I could just try it and see, but I thought I'd ask in case anyone already knows the answer. Thanks in advance!

**Comment by kevinmehall** [comment]
Yes, I've compiled WASM containing a rust-peg generated parser. `cargo build --target=wasm32-unknown-unknown` just works when it comes to procedural macros.

**Comment by aunyks** [comment]
That’s amazing! Thanks again.

**Comment by zm-cttae** [comment]
Anyone have an example of a WASM Rust PEG parser?
