### ISSUE TITLE
How do I count the tab depth

### ISSUE THREAD

**Issue by uselessgoddess** [kevinmehall/rust-peg#285]
I don't have access to `ParseState`. How do I hack this?

**Comment by kevinmehall** [comment]
For a language with significant whitespace, the recommended approach is to put a lexer in front that turns indentation changes into Indent / Dedent tokens, and then the grammar can handle those just like the `{` `}` of a C-like language.

See also https://github.com/kevinmehall/rust-peg/issues/223
