### ISSUE TITLE
Question: identifying unicode general categories

### ISSUE THREAD

**Issue by ethindp** [kevinmehall/rust-peg#286]
I've come across a grammar that, for identifiers, uses general categories instead of explicitly defining each possible character that can be used. Specifically, it is the Ada programming language that does this, though I'm pretty sure other grammars out there do it too. The specific productions that do this are as follows:

```ebnf
        identifier ::= 
           identifier_start {identifier_start | identifier_extend}

        identifier_start ::= 
             letter_uppercase
           | letter_lowercase
           | letter_titlecase
           | letter_modifier
           | letter_other
           | number_letter

        identifier_extend ::= 
             mark_non_spacing
           | mark_spacing_combining
           | number_decimal
           | punctuation_connector
```

What is the fastest and easiest process for matching something like this in a PEG? It would make sense to use GCs for this kind of thing especially if you want a language to be Unicode aware (and it also makes the grammar far easier to read). To date I've yet to come across a Rust crate that lets me do this and that doesn't require me to have the UCD on hand. One option I can think of would be to manually generate a function that uses a match expression to identify GCs, but this is clunky, complex, and generates well over a hundred thousand match arms, which is a bit much. Even condensing it into the set of characters for each class per match arm still will result in several hundred thousand alternative branches, which is ridiculous. The Rust standard library has some functions to assist with this (e.g. is_whitespace, is_digit, etc.) but this doesn't cover *all* GCs, and I don't know how extensive they are. Is this just a general problem that Unicode brings to the table or am I missing something really, really obvious?

**Comment by kevinmehall** [comment]
I've seen the [unicode-xid](https://unicode-rs.github.io/unicode-xid/unicode_xid/trait.UnicodeXID.html) crate used for this -- not sure if XID_Start / XID_Continue are the same sets you're looking for, but you could look at its implementation if you need something else.

With a function that tests a character and returns a `bool`, you can easily integrate it with rust-peg like this:

```
rule identifier() -> String 
    = quiet!{ i:$([c if c.is_xid_start()] [c if c.is_xid_continue()]*) { i.to_string() } }
    / expected!("identifier")
```
