### ISSUE TITLE
Values parsed inside span

### ISSUE THREAD

**Issue by Kile-Asmussen** [kevinmehall/rust-peg#297]
It would be really convenient to be able to do something like this:

```rust
rule with_span<T>(thing: rule<T>) -> (T, &'input str)
= span:$( val:thing() ) { (val, span) } ;
```

As it stands I've made this kludge:

```rust
rule with_span<T>(thing: rule<T>) -> (T, &'input str)
= span:&( $( thing() ) ) ) val:thing() { (val, span) } ;
```

Which apparently parses `thing()` twice.

**Comment by Mingun** [comment]
Probably it is better to return `Spanned<T>` from `$()`, where 
```rust
struct Spanned<T> {
  pub value: T,
  pub span: Span,
}
```

**Comment by Kile-Asmussen** [comment]
@Mingun Sure, but _how?_

**Comment by Mingun** [comment]
I mean, that currently rust-peg returns just `Span` in that case and it should be modified to return `Spanned<T>` (if I all understand correctly... I've not looked at the code).

**Comment by kevinmehall** [comment]
Duplicate of https://github.com/kevinmehall/rust-peg/issues/283. There's a potential wokaround there, but I think it might be worth adding syntax for this.
