### ISSUE TITLE
Matching EOF

### ISSUE THREAD

**Issue by shepherd1530** [kevinmehall/rust-peg#318]
I am tru=ying to write a parser for an INI file but I haven't been able to parse it correctly.

```
grammar ini() for str {
        rule _ = [' ' | '\t' ]*
        rule newline() = ['\n' | '\r']+
        rule character() -> char
            = c:['a'..='z' | 'A'..='Z' | '0'..='9' | '_' | '-' | '.' | '/'] { c }
        rule name() -> String
            = n:$(character()+) { n.to_string() }
        rule value() -> String
            = v:$(character()*) { v.to_string() }
        pub rule section() -> String
            = "[" s:name() "]" { s }
        pub rule entry() -> (String, String)
            = k:name() _ "=" _ v:value() { (k, v) }
        pub rule property() -> Vec<&'input str>
            = a:$((s:section() / e:entry())? newline() )* ![_] { a }
    }
```

This grammar matches an ini file successfully only if an extra blank line exists in the file like below.

```
[second_server]
document_root=/var/www/example.com
ip=
interface=eth1

```

Is this the intended behaviour or am I missing something?

**Comment by kevinmehall** [comment]
Your `property` rule requires a trailing newline inside of the repetition before it gets to the EOF.

You probably want something like this to allow the file to end without a newline:
```
pub rule property() -> Vec<&'input str>
            = a:$((s:section() / e:entry())? (newline() / ![_]) )* { a }
```

I'll also note that the use of the string capture `$` is a little weird here, given that `section` and `entry` return a value that you are ignoring. You probably want to call `entry` within `section` and return `(String, Vec<(String, String)>)` for the section headers and entries within.

**Comment by shepherd1530** [comment]
> want to call `entry` within `section` and return `(String, Vec<(String, String)>)` for the section headers and entries within

Thanks for the reply.

Your suggested changed resulted into an infinite loop warning

```
error: loops infinitely because loop body can match without consuming input
  --> src/peg/csv/ini.rs:20:66
   |
20 |             = a:$((s:section() / e:entry())? (newline() / ![_]) )* { a }
```

Can you also help with a snippet of the last part about composing the grammar to get a tuple like ```(String, Vec<(String, String)>)``` I am coming from pest and I haven't gotten the hang of this yet. Thanks.

**Comment by kevinmehall** [comment]
Ah, yeah, that error is because of the `?` making most of the repeat body optional, but the EOF continues to match (since unlike a character, it doesn't consume anything), allowing  the `*` to repeat infinitely at the end of the file.

Here's how I would structure an INI parser:

```rust
grammar ini() for str {
    rule _ = [' ' | '\t' ]*
    rule eol() = ['\n' | '\r']+
    rule character()
        = ['a'..='z' | 'A'..='Z' | '0'..='9' | '_' | '-' | '.' | '/']
    rule name() -> String
        = n:$(character()+) { n.to_string() }
    rule value() -> String
        = v:$(character()*) { v.to_string() }

    pub rule header() -> String
        = "[" s:name() "]" eol() { s }
    pub rule entry() -> (String, String)
        = k:name() _ "=" _ v:value() eol() { (k, v) }
    
    pub rule section() -> (String, Vec<(String, String)>)
        = h:header() s:entry()* { (h, s) }

    pub rule file() -> Vec<(String, Vec<(String, String)>)>
        = eol()? s:section()* {s}
}
```

You could define some structs to use instead of tuples if you wanted nicer return types.
