### ISSUE TITLE
Can't seem to access peg binary when peg is specified as cargo dependency

### ISSUE THREAD

**Issue by benjreinhart** [kevinmehall/rust-peg#33]
Sorry for posting this here, but I am unable to figure this out and so far the people in the rust IRC have not responded either.

I'm not sure how to access the peg binary when my project is using cargo to include peg as a dependency. Is there a standard way of doing this?

For instance, I have the following as a dependency in my `Cargo.toml` file:

```toml
[dependencies]
peg = "0.1.1"
```

It'd be nice if when I ran `cargo build` there was a directory of binary executables in `target`. Then I could just do `target/bin/peg my_grammar.rustpeg > src/grammar.rs`. 

Again, sorry this is also a question about Cargo in general, but I can't seem to figure this out.

**Comment by kevinmehall** [comment]
Closing in favor of #121
