### ISSUE TITLE
Stable sort for expected set entries in error messages

### ISSUE THREAD

**Issue by mcandre** [kevinmehall/rust-peg#340]
Hi,

I am seeing random orderings for the entries in the ExpectedSet, in parse error messages.

Can we please implement a stable sort of these entries, such as lexicographic, sort?

That way, when I retry the same parse command multiple times, I don't get what appear to be distinct, new error messages each time.

For example, BTreeSet is a Rust built-in collection offering stable sorting of our set elements.

https://doc.rust-lang.org/std/collections/struct.BTreeSet.html

**Comment by kevinmehall** [comment]
This was actually done last week in https://github.com/kevinmehall/rust-peg/pull/336. Will be in a release soon.

**Comment by kevinmehall** [comment]
Fixed in 0.8.2
