### ISSUE TITLE
warn on missing .PHONY entry for common target names

### ISSUE THREAD

**Issue by mcandre** [kevinmehall/rust-peg#341]
When "all" target exists, but is missing an entry jn .PHONY, recommend providing one.

This reduces the chances of accidentally skipping the rule's commands, in the case that a file path "all" is ever created.

Conversely, it is exceedingly rare that a genuine artifact "all" would be desired, in the vast majority of makefile projects.

Same for "test" and "install".

This mimicks the behavior of the checkmake linter. Without the detriment of demanding phony declarations when no such target is declared as a makefile rule, presently an open glitch in checkmake.

**Comment by kevinmehall** [comment]
Wrong repository?
