### ISSUE TITLE
general question about thread safety

### ISSUE THREAD

**Issue by mcandre** [kevinmehall/rust-peg#343]
This might sound dumb, but are rust-peg grammars safe to use directly for parsing multiple files concurrently, from different threads?

I am toying with the idea of keeping track of line number count for a linter application in my grammar. But I expect my app to receive multiple files to scan, and don't want the line number to get messed up when invoking the grammar's public rule multiple times.

In theory, I could wrap the counter in an atomic integer type. But I still need a way to inform the parser call of the (absolute) file path, so that it connects with the right counter for that file.

I am so lost, lol! But having fun learning.

**Update**

My current plan is to collect `position!()` into an offset struct field of the different nodes in my AST. *After* parsing, assuming a valid result, then I will build an index mapping byte offset ranges to line number. And then descending down the AST, updating a line struct field. Involves some boilerplate, a second linear scan of the original string, and any parse errors will still process in linear time. But it should more or less work, with the existing peg API.

**Comment by kevinmehall** [comment]
Yes, there's no state shared between calls to the parser, and it doesn't use `unsafe{}` so there's nothing to be concerned about with thread safety.
