### ISSUE TITLE
Binding captured strings?

### ISSUE THREAD

**Issue by j-james** [kevinmehall/rust-peg#349]
Currently in my grammar I have some lines that look like this:
```rust
rule empty() -> Type = k:"empty" {Type::Empty}
rule unit() -> Type = k:"unit" {Type::Unit}
rule boolean() -> Type = k:"bool" {Type::Boolean}
rule natural() -> Type = k:"nat" {Type::Natural}
rule integer() -> Type = k:"int" {Type::Integer}
rule kind() -> Type
 = k:(empty() / unit() / boolean() / natural() / integer()) {
    k
}
```

This is a somewhat gross workaround for not being able to inspect which string matched k. I would prefer to do it as so:
```rust
rule kind() -> Type
= k:("empty" / "unit" / etc) {
  match k { // k is (), which is not matchable
    "empty" => ...,
    etc
  }
}
```

Is there a better way to match captured strings that I've glossed over? If there isn't: would it be possible to change the `k:("str1" / "str2")` syntax to allow binding the strings, or introduce a new construct?

**Comment by kevinmehall** [comment]
`k:$("empty" / "unit") { match k { ... }}`

The `$` operator captures the slice of input matched by an expression.

**Comment by j-james** [comment]
Oh nice, I missed that in the documentation, thanks! I also had another question that I couldn't find in the docs: is it possible to manually raise a ParseError from within a rule?

**Comment by kevinmehall** [comment]
`expected!("something")`

https://docs.rs/peg/latest/peg/#failure-reporting

**Comment by j-james** [comment]
Ah, I meant inside a `{ ... }`, whoops!

**Comment by kevinmehall** [comment]
See the `{? ... }` syntax, like in the `number` example in the README
