### ISSUE TITLE
help with misleading expected set

### ISSUE THREAD

**Issue by mcandre** [kevinmehall/rust-peg#350]
Hi,

I am continuing to refine my makefile grammar.

https://github.com/mcandre/unmake

According to the POSIX make specification, a rule cannot be empty. It must have at least a prerequisite, an inline command, and/or an indented command.

That is, in make, `all:` is unacceptable input by itself, but `all: build`, `all:\n\techo Hi`, and `all:;echo Hi` are acceptable inputs.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html

I am able to enforce this requirement in the grammar, and have unit tests verifying the grammar's behavior.

_However_, peg presents the wrong expected set for empty rules.

peg should include a semicolon (`;`) in the expected set. The grammar allows for a semicolon to begin an inline rule command. But for some reason, peg does not present semicolon as a possibility.

I even tried to override the formatting, via the `expected!()` macro. But the macro is having no effect on the parse error message.

**Comment by kevinmehall** [comment]
I tested your grammar (without the surrounding code) and it does expect `;` when parsing `"all:"`:

```
println!("{}", parser::parse("all:").unwrap_err());
->
error at 1:5: expected one of " ", "#", "$(", "${", ";", "\n", "\t", [^ (' ' | '\t' | ':' | ';' | '#' | '\r' | '\n' | '\\')]
```

My guess is that you're testing this in middle of a file or your file has a trailing newline. Note that the position and expected set are different when parsing `"all:\n"`:

```
error at 2:1: expected one of "#", "\n", "\t"
```

The error position is now after the newline, and indeed if you add a semicolon there, (`"all:\n;"`), it's not accepted at that position.

As it tries alternatives in order with the `/` operator, it maintains an expected set and a max error position. When a literal, match expression, `expected!()` or `{? }` fails at position `p`:
  * if `p` is less than the max error position, nothing is added
  * if `p` is equal to the max error position, the item is added to the expected set
  * if `p` is greater than the max error position, the max error position is moved forward, the expected set is cleared, and the item is added

If before or after failing to match the semicolon, another alternative is tried, and successfully matches a `\n` at 1:5, but that alternative then fails at 2:1, it will bump the max error position, and the expected set will only include things that are tried at 2:1.

Your grammar looks somewhat inconsistent with its handling of whitespace -- you probably what to accept whitespace before the semicolon.

**Comment by mcandre** [comment]
You raise a fair point about `all:\n;`, and that is worth testing in its own right. But that's not what was triggering the peg behavior described.
