### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by fzandona** [kevinmehall/rust-peg#36]
I'm trying to run rust-peg but it fails with:

$ RUST_BACKTRACE=1 ./target/peg src/grammar.rustpeg

thread '<main>' has overflowed its stack
[1]    29743 illegal hardware instruction  RUST_BACKTRACE=1 ./target/peg src/grammar.rustpeg

This is with the latest nightly rust build:

$ rustc --version
rustc 0.13.0-nightly (62fb41c32 2014-12-23 02:41:48 +0000)

Any idea what could be going on here?

Thanks!

**Comment by kevinmehall** [comment]
If you're still interested in this (sorry for taking so long to reply), check your grammar for left-recursive rules like `x = x "+" y` as those result in infinite recursion in PEG.

https://en.wikipedia.org/wiki/Parsing_expression_grammar#Indirect_left_recursion
