### ISSUE TITLE
Matching byte-ranges

### ISSUE THREAD

**Issue by untitaker** [kevinmehall/rust-peg#41]
For example, https://tools.ietf.org/html/rfc5234 defines several byte-ranges to match.

It'd be nice if rust-peg supported a similar syntax:

    Hence:

         DIGIT       =  %x30-39

    is equivalent to:

         DIGIT       =  "0" / "1" / "2" / "3" / "4" / "5" / "6" /

                        "7" / "8" / "9"

**Comment by daramos** [comment]
Maybe I'm confused, but what's the difference between this and doing
`DIGIT = [0-9]`?

**Comment by kevinmehall** [comment]
Code point ranges are already supported with the syntax `[\u{30}-\u{39}]`. (Which is equivalent to `[0-9]`)

Note that this library operates on unicode code points, not bytes.

**Comment by untitaker** [comment]
Interesting, I didn't consider to use all kinds of literals in such an expressio. Thanks!
