### ISSUE TITLE
How to make created module public?

### ISSUE THREAD

**Issue by NobbZ** [kevinmehall/rust-peg#43]
Lets say I have this in my `libs.rs`:

```rs
peg! parsemod(r#"
  #[pub]
  expr = …
  …
"#);
```

And I want to use it from `main.rs`:

```rs
extern crate mycrate;
use mycrate::parsemod;
fn main () {
  let parsed = parsemod::expr("Foo");
}
```

Building this with `cargo build` results in ``module `parsemod` is private``.

How can I make `parsemod` public?

**Comment by untitaker** [comment]
Did you try the "pub" keyword?

I wouldn't directly export your parser from the crate, but rather wrapper functions. That way you're not prone to API changes in rust-peg.

**Comment by NobbZ** [comment]
I tried pub keyword in front of and behind peg! Macro, same problem. But
yes, the idea with building a wrapper function in another module came to me
too while driving home ;-)
Am 22.01.2015 12:34 schrieb "Markus Unterwaditzer" <notifications@github.com

**Comment by NobbZ** [comment]
OK, using a wrapper works! Thank you!
