### ISSUE TITLE
"skip"-rule

### ISSUE THREAD

**Issue by NobbZ** [kevinmehall/rust-peg#45]
Is there an easy way to always skip whitespace or do I need to tell explicitely that it is allowed but not needed between every token?

**Comment by untitaker** [comment]
There's no way to always tell it to skip whitespace. I use a ``__`` rule for representing whitespace, I think the parser inside rust-peg does too.

**Comment by NobbZ** [comment]
OK, so I have to through in `whitespace*` (or whatever it is called) everywhere. This is somewhat noisy but I can live with it.

Thank you!
