### ISSUE TITLE
Error: Expected HashSet

### ISSUE THREAD

**Issue by alexchandel** [kevinmehall/rust-peg#48]
I'm hitting an error with rust-peg. It's expecting a newline in a statement that shouldn't need one:

```rust
main.rs:56:1: 123:5 error: Error at Line 58:12: Expected HashSet {"\u{2029}", "\r\n", "\u{2028}", "\n", "\r"}
main.rs:56 peg! dot(r#"
main.rs:57 #[pub]
main.rs:58 graph -> DotGraph
main.rs:59 	= __ "strict"? __ gt:GraphType __ id:ID? __ "{" __ stmts:stmt_list __ "}" __
main.rs:60 	{
main.rs:61 		DotGraph::new(id, gt, stmts)
           ...
```

**Comment by untitaker** [comment]
I can't reproduce this. Could you provide a minimal example?

**Comment by alexchandel** [comment]
The file: https://gist.github.com/alexchandel/538a6a83c8742d1f0f10

**Comment by untitaker** [comment]
The real issue appears to be that you use tabs while rust-peg doesn't recognize this as whitespace.

**Comment by alexchandel** [comment]
@untitaker Don't think so, since I can compile minimal examples with tabs.

**Comment by alexchandel** [comment]
Actually, I think I solved it, but now I get a hundred errors along the lines of:
```rust
<quote expansion>:1:1: 1:17 error: use of undeclared type name `DotGraph`
<quote expansion>:1 name_89,ctxt_0
                    ^~~~~~~~~~~~~~~~
main.rs:1:1: 124:1 note: in expansion of peg!
main.rs:56:1: 120:5 note: expansion site
<quote expansion>:163:187: 163:221 error: failed to resolve. Use of undeclared type or module `DotGraph`
<quote expansion>:163                                                                                                                                                                                           name_89,ctxt_0::name_92,ctxt_0(name_316,ctxt_0,
                                                                                                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.rs:1:1: 124:1 note: in expansion of peg!
main.rs:56:1: 120:5 note: expansion site
```

Does rust-peg not support returning user types?

**Comment by kevinmehall** [comment]
The parse error is actually with the character escape syntax `\200-\377` on [line 111](https://gist.github.com/alexchandel/538a6a83c8742d1f0f10#file-main-rs-L111) of your gist. It reports the error in the correct position when the grammar is in a standalone file, so this is a bug in error reporting in the syntax extension (it's reporting the error at the start of the grammar string).

The syntax for unicode escapes is [just like Rust's](https://github.com/rust-lang/rfcs/blob/master/text/0446-es6-unicode-escapes.md)

**Comment by untitaker** [comment]
Yeah, I was just about to post about the escape sequences.

>Does rust-peg not support returning user types?

You need to ``use`` them inside your peg parser.

**Comment by kevinmehall** [comment]
The code it generates is wrapped in a `mod`, so you have to `use super::DotGraph;` at the top of your grammar.

**Comment by alexchandel** [comment]
Ah ok, I looked but couldn't find any documentation on whether rust-peg had a `use`.
