### ISSUE TITLE
Can't import from parent module

### ISSUE THREAD

**Issue by gsingh93** [kevinmehall/rust-peg#61]
My main file looks like this:

```
#![feature(plugin, core)]
#![plugin(peg_syntax_ext)]

enum BinOp {
    AddOp,
    SubOp,
    MulOp,
    DivOp,
}

peg_file! lisp("grammar.rustpeg");
```

But I can't access `BinOp` with `use super::BinOp` in my grammar.rustpeg file:

```
Compiling lisp v0.0.1 (file:///mnt/ubuntu/home/gulshan/code/lang/rust/lisp)
<quote expansion>:1:1: 1:17 error: use of undeclared type name `BinOp`
<quote expansion>:1 name_66,ctxt_0
```

**Comment by omeili** [comment]
super::<type> works for me, when the macro is inline in peg 0.3.0, not sure whether this has also been fixed for included grammars.

**Comment by gsingh93** [comment]
Yea, this is working for me now too. Not sure if I was doing something wrong originally or this got fixed.
