### ISSUE TITLE
/ expression ordering gives different results when there is a leading partial match

### ISSUE THREAD

**Issue by okey** [kevinmehall/rust-peg#65]
From the readme:
> _`e1 / e2 / e3` - Try to match e1. If the match succeeds, return its result, otherwise try e2, and so on._

From this I expected e2 to begin matching from the same place as e1 began (&c), although that may not be the case... consider the following:

    foo -> String
      = bar / baz

    qux -> String
      = baz / bar

    bar -> String
      = [a-z]+[A-Z]+ { match_str.to_string() }

    baz -> String
      = [a-z]+ { match_str.to_string() }

Testing `foo` and `qux` gives different results:

    println!("{:?}", foo("abcABC"));
    println!("{:?}", foo("abc"));

>    Ok("abcABC")
>    Ok("abc")

    println!("{:?}", qux("abcABC"));
    println!("{:?}", qux("abc"));

>    Err(ParseError { line: 1, column: 1, offset: 0, expected: {"[a-z]"} })
>    Err(ParseError { line: 1, column: 1, offset: 0, expected: {"[a-z]"} })

The latter behaviour surprised me (compared to the former case, and compared to `[a-z]+ / [A-Z]+`), and I'm not sure if it is intended.

[Wikipedia](http://en.wikipedia.org/wiki/Parsing_expression_grammar#Operational_interpretation_of_parsing_expressions)
> The choice operator e1 / e2 first invokes e1, and if e1 succeeds, returns its result immediately. Otherwise, if e1 fails, then the choice operator backtracks to the original input position at which it invoked e1, but then calls e2 instead, returning e2's result.

**Comment by kevinmehall** [comment]
Your interpretation of the choice operator is correct.

When I run this program:

```.rs
#![feature(plugin, core, collections)]
#![plugin(peg_syntax_ext)]

use parser::*;
peg! parser(r#"
#[pub]
foo -> String
  = bar / baz

#[pub]
qux -> String
  = baz / bar

bar -> String
  = [a-z]+[A-Z]+ { match_str.to_string() }

baz -> String
  = [a-z]+ { match_str.to_string() }
"#);

fn main() {
    println!("{:?}", foo("abcABC"));
    println!("{:?}", foo("abc"));

    println!("{:?}", qux("abcABC"));
    println!("{:?}", qux("abc"));

}
```

I'm getting a different set of failures and the results are (mostly) as I would expect them.

```
Ok("abcABC")
Ok("abc")
Err(ParseError { line: 1, column: 4, offset: 3, expected: {"[a-z]"} })
Ok("abc")
```

The `qux("abcABC")` case fails to match because `qux` tries `baz` first and `baz` successfully matches "abc", so it doesn't backtrack. Then, there is no rule to match the remaining "ABC". The `expected` field would ideally also include "EOF", but the failure to match is correct.

**Comment by okey** [comment]
> I'm getting a different set of failures

That's because I copied the wrong output by mistake. Terribly sorry about that. My results are the same as yours.

> The qux("abcABC") case fails to match because qux tries baz first and baz successfully matches "abc", so it doesn't backtrack. Then, there is no rule to match the remaining "ABC". The expected field would ideally also include "EOF", but the failure to match is correct.

Ah, that makes sense, although I'm still a bit surprised that the partial match prevents backtracking given that 

    println!("{:?}", baz("abcABC"));

is considered a failure

> Err(ParseError { line: 1, column: 4, offset: 3, expected: {"[a-z]"} })

because it doesn't match the _whole_ string.

**Comment by kevinmehall** [comment]
PEGs don't do arbitrary backtracking like regex; they only backtrack when a choice arm fails, and in this case, the choice successfully matches "abc" and the parser moves on.

https://stackoverflow.com/questions/24773462/how-does-backtracking-work-in-peg-js-with-example
