### ISSUE TITLE
Custom error messages or rule names

### ISSUE THREAD

**Issue by kevinmehall** [kevinmehall/rust-peg#73]
A hack to achieve custom error messages after #71:

```
_binop
    = "+" / "-" / "*" / "/" / ">=" / "<=" / "==" / "!=" / ">" / "<"

binop
    = op:_binop? {? match op {
        Some(op) => Ok(op),
        None => Err("binary operator"),
    }}
```

peg.js supports associating human-readable names with rules which are used in the "expected" error message.

`integer "integer" = [0-9]+`
`Line 1, column 1: Expected integer but "a" found.`

Since rust-peg already uses pseudo-rust attributes, this could perhaps be:

```
#[expected = "integer"]
integer = [0-9]+
```

if we wanted to clone the peg.js semantics.

**Comment by beefsack** [comment]
@kevinmehall, I'm currently using rust-peg to write a parser which parses user input and am currently trying to come up with a method for end-user friendly human readable error messages.  Ideally, these messages would be somewhat verbose and include extra context or suggestions to help the user.

Do you think this enhancement would help satisfy a use case like that?

**Comment by kevinmehall** [comment]
Added in dcd045d901deff35f8bd0537d0cd3d783cd928a1. The `#quiet<e>` expression causes failures in `e` to be ignored for the purpose of error reporting. The `#expected("foo")` expression fails to parse and adds "foo" to the set of tokens expected at its position.

You can use `#quiet` alone to ignore rules that you don't want to see in error messages:
```
ws = #quiet<[ \r\n]+>
```

or use `#quiet` and `#expected` together to provide an alternate error message for a rule:

```
identifier = #quiet<[a-z][a-z0-9_]*> / #expected("identifier')
```
