### ISSUE TITLE
Ignore unmatched curly braces in strings and comments in Rust code blocks

### ISSUE THREAD

**Issue by mohtar** [kevinmehall/rust-peg#81]
Test case:

```
foo -> &str = "foo" {"}"}
```

Running `peg` against this grammar yields the following error:

```
$ peg test.rustpeg 
Error parsing language specification: error at 2:24: expected one of `\r`, `;`, `/*`, `[a-z]`, `#[export]`, `[A-Z]`, `\r\n`, `\u{2028}`, `#[pub]`, `\n`, `\u{2029}`, `/`, `_`, `//`, `[ \t\u{a0}\u{feff}\u{1680}\u{180e}\u{2000}-\u{200a}\u{202f}\u{205f}\u{3000}]`
```

It seems like the problem is in the `"}"` part of the grammar. If I replace it with something else (e.g. `"a"`), the code generation works.

This happens to v0.2.3

**Comment by kevinmehall** [comment]
The code blocks currently need to contain matched brackets, because it doesn't fully parse the Rust code inside them. You can probably work around this by including `/*{*/` before the string literal.

**Comment by suhr** [comment]
I believe this can be workarounded by something like `comment / string / (braced "") / nonBraceCharacters`. No need to parse the rust code fully.

**Comment by ebfull** [comment]
Maybe add "raw code blocks" like "raw string literals" in rust?

```rust
#{"}"}#
```

**Comment by kevinmehall** [comment]
No longer a problem with proc-macros
