### ISSUE TITLE
Support for threading a context object through to action code

### ISSUE THREAD

**Issue by kevinmehall** [kevinmehall/rust-peg#84]
Allow an object passed to the top-level parse call to be threaded through all parse functions and accessible to the action code.

~~~With a `#![context(T)]` at the top of the grammar source, all exposed parse functions  gain an extra argument of type `T`, which is exposed to actions as the `context` variable~~~.

Use cases: string interners, source mapping.

**Comment by Botev** [comment]
Hi,
I really enjoy the rust-peg as I'm new to rust and I'm trying to build a small parser for a subset of matlab. Would be very delighted if this becomes an option, as I need to keep track of a variable table and a few more "meta" structures which to be accessible to every rule in the parser.
Also could you provide an example of using the context from a stand alone generated parser, since I do not want my cargo to depend on Nightly, I would much rather prefer to have it standalone build and than work with the parser source. 
Btw sorry, I'm new to rust and partially to github, do not know if this is the right place etc. Anyway, thanks for the package!

**Comment by ebfull** [comment]
There might be a use case for a context object which is generic, especially if we need to use closures.

**Comment by ebfull** [comment]
I needed global context objects for an indentation-scoped grammar, which is context-sensitive. Indentation is a "grammar local" implementation detail, and I'm not sure supplying an initial indentation level is the responsibility of end users of my parser.

I've [hacked together](https://github.com/ebfull/rust-peg/tree/context-objects) static context rules which are initialized when ParserScope is created and available to all rules. I will make some improvements to efficiency and add tests, after some feedback of the overall design. (One potential problem is whether or not we should allow shadowing of context object bindings by tagged expressions.)

Here's my indentation example:

```rust
use super::Statement;
use super::Line;
use std::char;

#[context]
indentation_level -> usize = {0}

#[pub]
parse -> Vec<Statement<'input>>
    = s:statements {s}

statements -> Vec<Statement<'input>>
	= s:statement+ {s}

statement -> Statement<'input>
    = l:line children:statement_children? {Statement{line: l, children: children}}

statement_children -> Vec<Statement<'input>>
	= INC_INDENT children:statements DEC_INDENT {children}
	/ DEC_INDENT {? Err("children")}

line -> Line<'input>
	= SAME_INDENT line:line_expr __? EOL? {line}
	/ SAME_INDENT EOL {Line{s: match_str}}

line_expr -> Line<'input>
	= ident:ident {Line{s: ident}}

ident -> &'input str
	= [a-z]+ {match_str}

EOL -> ()
    = "\r\n" / "\n" / "\r" {()}

INDENTATION -> usize
    = tabs:("    "/"\t")* { tabs.len() }

INC_INDENT -> ()
	= {*indentation_level = *indentation_level + 1; ()}

SAME_INDENT -> ()
    = i:INDENTATION {? if i == *indentation_level { Ok(()) } else {Err("same indentation")}}

DEC_INDENT -> ()
	= {*indentation_level = *indentation_level - 1; ()}

__ -> ()
	= (" "/"\t")+ {()}

```

**Comment by ihrwein** [comment]
I'd use this to pass a factory implementation to the grammar. This way the grammar would be generic and the factory could create different implementations from the same grammar rules.

**Comment by ehiggs** [comment]
Use case: Filtering the parsing to what's relevnt. e.g. parsing httpd logs, one might want to throw away all the non ERROR logs so `if loglevel==ERROR { None } else { Some(match_str.to_string())`

Or: counting the number of fields in a csv file quickly.

**Comment by kevinmehall** [comment]
Another option available now is to use [thread local storage](https://github.com/alexcrichton/scoped-tls).

If I were to add something like this, it would need to be redesigned. I'm moving away from all the unhygenic magic variable names like `context` and `match_str` in 0.4.

Separately from passed-in context, I plan to implement mutable state variables that are rolled back with backtracking for cases like whitespace-sensitive grammars. I think your "counting the number of fields in a csv file" case would fall under this category.

**Comment by kevinmehall** [comment]
Prototype for design feedback at #160. I plan to add checks to prevent you from shadowing context arguments with capture variables to provide better errors than rustc would on the generated code.

[Documentation](https://github.com/kevinmehall/rust-peg/blob/context-args/README.md#context-arguments) | [Test / Example](https://github.com/kevinmehall/rust-peg/blob/context-args/peg-syntax-ext/tests/grammar_args.rs)

**Comment by ehiggs** [comment]
The interface looks like it makes sense since you don't have to repeat the arguments all the time as the flow of control passes through all the rules.
