### ISSUE TITLE
Removing IdentTT

### ISSUE THREAD

**Issue by Manishearth** [kevinmehall/rust-peg#95]
I'm considering removing `IdentTT` [here](https://github.com/rust-lang/rust/pull/26294). Do you have any objections to that?

The syntax would have to change to something like 

```
peg! {
 mod modname(....)
}

```

**Comment by kevinmehall** [comment]
Well, the alternative is slightly uglier, but it's not worth keeping in the compiler if rust-peg is the only thing using it.

**Comment by norcalli** [comment]
This could probably be closed now.
