### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by ihrwein** [kevinmehall/rust-peg#96]
When I try to use the following contents `cargo test` never returns:

```
#![feature(plugin)]
#![plugin(peg_syntax_ext)]

peg! line(r#"

#[pub]
line -> Vec<&'input str>
  = line_parts* 

line_parts -> &'input str
  = literal
  / command

#[pub]
literal -> &'input str
  = l:(!"$(" .)* { match_str }

command -> &'input str
  = "$(" c:inside_command ")" { c }

inside_command -> &'input str
  = [a-zA-Z0-9_-]+ { match_str }

"#);

#[test]
fn main() {
  assert_eq!(line::literal("foo ").ok().unwrap(), "foo ");
  assert_eq!(line::literal("foo \n").ok().unwrap(), "foo \n");
  assert_eq!(line::line("foo $(a)").ok().unwrap(), vec!["foo ", "a"]);
}
```

I think the problem is using the `.*` expression.

Edit: The example was simplified based on @jonas-schievink 's suggestions.

**Comment by jonas-schievink** [comment]
In PEG, .* doesn't backtrack, so .* will always match everything until the end of the input (it also cannot fail to match). This means that your rules don't do what you want them to do, but it shouldn't create an infinite loop.

**Comment by ihrwein** [comment]
@jonas-schievink I didn't know that, thanks! Do you have any idea how should I express the following: I want to match everything until I find `$(`.

**Comment by jonas-schievink** [comment]
```rust
rule = (!"$(" .)*
```
This uses negative lookahead and matches the `.` only if "$(" does not match at that position

**Comment by ihrwein** [comment]
Thanks, I'm one step closer :) Now I replaced the `literal` rule with the following one, but it's also stuck in infinite loop:

```
#[pub]
literal -> &'input str
  = l:(!"$(" .)* { match_str }
  / l:all_chars { l }
```

**Comment by jonas-schievink** [comment]
The problem could be that all_chars matches the empty string (at the end of the input), and `line_parts*` calls it as long as it matches (which is always). Since .* doesn't really make sense in PEG anyways, I suggest that you remove the all_chars rule altogether.

**Comment by ihrwein** [comment]
I wanted to use that to handle line endings, like this: `foo $( .. ) bar`. I thought it will match ` bar` when the first rule doesn't match.

**Comment by jonas-schievink** [comment]
Well, as long as `line_parts` can match the empty string, you can't use `line_parts*` anywhere (we could possibly warn if we detect this), so you'll have to rewrite your grammar somehow.

**Comment by ihrwein** [comment]
I've managed to make it work:

```
#![feature(plugin)]
#![plugin(peg_syntax_ext)]

peg! line(r#"

#[pub]
line -> Vec<&'input str>
  = line_parts+
  / "" { vec!("") }

line_parts -> &'input str
  = l:(!"$(" .)+ { match_str }
  / "$(" c:inside_command ")" { c }

command -> &'input str
  = "$(" c:inside_command ")" { c }

inside_command -> &'input str
  = [a-zA-Z0-9_-]+ { match_str }

"#);

#[test]
fn main() {
  assert_eq!(line::line("foo ").ok().unwrap(), vec!["foo "]);
  assert_eq!(line::line("foo \n").ok().unwrap(), vec!["foo \n"]);
  assert_eq!(line::line("").ok().unwrap(), vec!(""));
  assert_eq!(line::line("$(abba)").ok().unwrap(), vec!("abba"));
  assert_eq!(line::line("foo $(a)").ok().unwrap(), vec!["foo ", "a"]);
  assert_eq!(line::line("foo $(a)").ok().unwrap(), vec!["foo ", "a"]);
  assert_eq!(line::line("foo $(a)$(bb)").ok().unwrap(), vec!["foo ", "a", "bb"]);
  assert_eq!(line::line("foo $(a)$(bb)c").ok().unwrap(), vec!["foo ", "a", "bb", "c"]);
}
```

@jonas-schievink  Should I close this issue? You may use this snippet as a unit test if you want. Thanks for your help!

**Comment by jonas-schievink** [comment]
No problem! Sure, you can close this. I think the tests and bootstrap already cover everything you used, so we don't need this as another unit test :)

**Comment by ihrwein** [comment]
Okay!
