### ISSUE TITLE
Allowing grouping of expressions by some brackets

### ISSUE THREAD

**Issue by Botev** [kevinmehall/rust-peg#97]
So this is quite straight forward, I know it is more of an echancement rather than anything else, but it would be nice if we can have some way of grouping things, so that for instance you can write something like:
ID / (LBRACE ID ++ COMMA RBRACE)

**Comment by jonas-schievink** [comment]
I don't exactly understand what you mean. You can already use parentheses to group expressions like this:

```rust
rule = var:([a-z]+ [0-9] {match_str})
```

In the example you gave, you can leave out the parens, since the precedence of `/` is quite low.

**Comment by Botev** [comment]
Hmm when I run the peg executable on my grammar the line:
`statementList = (statement | LINECOMMENT)`
Get's the error:

expected one of `\u{2029}`, `->`, `[ \t\u{a0}\u{feff}\u{1680}\u{180e}\u{2000}-\u{200a}\u{202f}\u{205f}\u{3000}]`, `++`, `&`, `+`, `\n`, `//`, `[A-Z]`, `**`, `)`, `\"`, `?`, `*`, `(`, `\'`, `/`, `=`, `{`, `\r`, `$`, `:`, `[a-z]`, `[`, `.`, `\u{2028}`, `/*`, `!`, `_`, `\r\n`

**Comment by Botev** [comment]
Ok, aparently for some reason I have switched to one of the dev branches some time ago and didn't go back and update, so its an issue which does not come in the main.
