### ISSUE TITLE
Auto generated issue for statements related to ? symbol

### ISSUE THREAD

**Issue by botev** [kevinmehall/rust-peg#99]
The grammar rule
`statementList = ( (statement NL) / (LINECOMMENT NL) )*`
works as a charm. How ever the following rule is problematic: 
`statementList = ( (statement NL?) / (LINECOMMENT NL) )*`
because in the generated method the NL? returns a Option<()> rather than (), e.g. it get passed up in the following way:
`let choice_res =
                        {
                            let seq_res = parse_statement(input, state, pos);
                            match seq_res {
                                Matched(pos, _) => {
                                    match parse_NL(input, state, pos) {
                                        Matched(newpos, value) => {
                                            Matched(newpos, Some(value))
                                        }
                                        Failed => { Matched(pos, None) }
                                    }
                                }
                                Failed => Failed,
                            }
                        };`

Now since the actual signature of the functions is Result<()> and we are returning the compiler can not determine what type is choice_res () or Option<()>.

**Comment by jonas-schievink** [comment]
If I'm not mistaken you can just do `statementList = ( (statement NL? {}) / (LINECOMMENT NL) )*`. The empty code block returns `()` and changes the result of the rule to match the other alternative.

**Comment by Botev** [comment]
Yeah, that is correct, I mean it's not really a big problem to work around, but maybe at least mention it on the wiki page, since it took me quite a while (also digging in the auto gen code) until I understood while it was not working.
